// Schema.voices.Add("Class", "Text", "Real Text.", "sound")

local function AddVoice(text, realtext, sound)
    Schema.voices.Add("CivilProtection", text, realtext, sound)
end

AddVoice("11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
AddVoice("404ZONE", "404 zone.", "npc/metropolice/vo/404zone.wav")
AddVoice("ACQUIRINGVISUAL", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
AddVoice("AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
AddVoice("AFFIRMATIVE2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav")
AddVoice("10-4", "10-4.", "npc/metropolice/vo/10-4.wav")
AddVoice("AIRWATCH505", "Dispatch we need airwatch, subject is 505.", "npc/metropolice/vo/airwatchsubjectis505.wav")
AddVoice("YOU CAN GO", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
AddVoice("ALLUNITSATBOL", "All units at BOL, we have 34s at", "npc/metropolice/vo/allunitsbol34sat.wav")
AddVoice("CLOSEONSUSPECT", "All units close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
AddVoice("ALLUNITSCODE2", "All units code 2.", "npc/metropolice/vo/allunitscode2.wav") // same as above
AddVoice("ALLUNITSMAINTAINTHISCP", "All units maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
AddVoice("ALLUNITSMOVEIN", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav")
AddVoice("REPORTLOCATIONSUSPECT", "All units report locations of suspect.", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
AddVoice("ALLUNITSATLOCATIONCODE3", "All units at location, respond at code 3!", "npc/metropolice/vo/allunitsrespondcode3.wav")
AddVoice("AMPUTATE", "Amputate.", "npc/metropolice/vo/amputate.wav")
AddVoice("ANTICITIZEN", "Anti-Citizen.", "npc/metropolice/vo/anticitizen.wav")
AddVoice("PICKUP647E", "Anyone else pick up uh.. 647E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
AddVoice("APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
AddVoice("ATCHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
AddVoice("BACKUP", "Backup.", "npc/metropolice/vo/backup.wav")
AddVoice("BLOCK", "Block.", "npc/metropolice/vo/block.wav")
AddVoice("BLOCKCOHESIVE", "Block is holding cohesive", "npc/metropolice/vo/blockisholdingcohesive.wav")
AddVoice("BREAKCOVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
AddVoice("CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
AddVoice("CANALBLOCK", "Canal Block.", "npc/metropolice/vo/canalblock.wav")
AddVoice("CATCHBLIP", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav")
AddVoice("CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
AddVoice("CHECKFORMISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
AddVoice("CHUCKLE", "*Chuckle*", "npc/metropolice/vo/chuckle.wav")
AddVoice("CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
AddVoice("CLEARCODE100", "Clear and Code 100.", "npc/metropolice/vo/clearandcode100.wav")
AddVoice("CLEARNO647", "Clear no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
AddVoice("CODE100", "Code 100.", "npc/metropolice/vo/code100.wav")
AddVoice("CODE7", "Code 7.", "npc/metropolice/vo/code7.wav")
AddVoice("CONDEMNEDZONE", "Condemned zone.", "npc/metropolice/vo/condemnedzone.wav")
AddVoice("CONTACTWITH243", "Contact with 243 suspect, my 10-20 is", "npc/metropolice/vo/contactwith243suspect.wav")
AddVoice("CONTROL100", "Control is 100 percent at location, no sign of 647E.", "npc/metropolice/vo/control100percent.wav")
AddVoice("CONTROLSECTION", "Control Section.", "npc/metropolice/vo/controlsection.wav")
AddVoice("CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
AddVoice("COPY", "Copy.", "npc/metropolice/vo/copy.wav")
AddVoice("COVERMEIN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
AddVoice("AIRWATCHBOL243", "CP, we need airwatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
AddVoice("CPCOMPROMISED", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
AddVoice("CPOVERRUN", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
AddVoice("CPLOCATIONREPORT", "CP requests all units uh.. location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
AddVoice("CPESTABLISHPERIMETER", "CP, we need to establish a perimeter at.", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
AddVoice("63TRESSPASS", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
AddVoice("DBCOUNT", "DB count is.", "npc/metropolice/vo/dbcountis.wav")
AddVoice("DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav")
AddVoice("DESERVICEDAREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
AddVoice("DESIGNATESUSPECTAS", "Designate suspect as.", "npc/metropolice/vo/designatesuspectas.wav")
AddVoice("DESTROYTHATCOVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
AddVoice("DISMOUNTINGHARDPOINT", "Dismounting Hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
AddVoice("DISPATCH10-78", "Dispatch, I need 10-78. Officer in trouble!", "npc/metropolice/vo/dispatchineed10-78.wav")
AddVoice("DISTRIBUTIONBLOCK", "Distribution Block.", "npc/metropolice/vo/distributionblock.wav")
AddVoice("DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
AddVoice("DONTMOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
AddVoice("8", "Eight", "npc/metropolice/vo/eight.wav")
AddVoice("18", "Eighteen", "npc/metropolice/vo/eighteen.wav")
AddVoice("80", "Eighty", "npc/metropolice/vo/eighty.wav")
AddVoice("11", "Eleven", "npc/metropolice/vo/eleven.wav")
AddVoice("EXAMINE", "Examine.", "npc/metropolice/vo/examine.wav")
AddVoice("EXPIRED", "Expired.", "npc/metropolice/vo/expired.wav")
AddVoice("EXTERNALJURISDICTION", "External Jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
AddVoice("15", "Fifteen", "npc/metropolice/vo/fifteen.wav")
AddVoice("50", "Fifty", "npc/metropolice/vo/fifty.wav")
AddVoice("FINALVERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
AddVoice("FINALWARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
AddVoice("FIRINGEXPOSETARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
AddVoice("FIRSTWARNINGMOVE", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
AddVoice("5", "Five.", "npc/metropolice/vo/five.wav")
AddVoice("4", "Four.", "npc/metropolice/vo/four.wav")
AddVoice("14", "Fourteen.", "npc/metropolice/vo/fourteen.wav")
AddVoice("40", "Fourty", "npc/metropolice/vo/fourty.wav")
AddVoice("11-44INBOUND", "Get that 11-44 inbound, we are cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
AddVoice("GETDOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
AddVoice("GETOUT", "Get out of here.", "npc/metropolice/vo/getoutofhere.wav")
AddVoice("TAKEALOOK", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav")
AddVoice("10-107TAG", "Got a 10-107 here, send airwatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
AddVoice("GOTHIMAGAIN", "Got him again, suspect is 10-20 at.", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
AddVoice("ONEACCOMPLICE", "I got one accomplice here.", "npc/metropolice/vo/gotoneaccomplicehere.wav")
AddVoice("GRENADE!", "Grenade!", "npc/metropolice/vo/grenade.wav")
AddVoice("HARDPOINTSCANNING", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
AddVoice("HELP!", "Help!", "npc/metropolice/vo/help.wav")
AddVoice("HERO", "Hero!", "npc/metropolice/vo/hero.wav")
AddVoice("HESGONE148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav")
AddVoice("RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav")
AddVoice("UPTHERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
AddVoice("HIGHREGION", "High priority region,", "npc/metropolice/vo/highpriorityregion.wav")
AddVoice("10-14DUTY", "Holding on 10-14 duty, code 4.", "npc/metropolice/vo/holdingon10-14duty.wav")
AddVoice("HOLDIT", "Hold it!", "npc/metropolice/vo/holdit.wav")
AddVoice("HOLDTHERE", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
AddVoice("HOLDPOSITION", "Protection team, hold this position!", "npc/metropolice/vo/holdthisposition.wav")
AddVoice("HAVE10-30", "I have a 10-30 at my 10-20, respond code 2", "npc/metropolice/vo/ihave10-30my10-20responding.wav")
AddVoice("INDUSTRIALZONE", "Industrial Zone.", "npc/metropolice/vo/industrialzone.wav")
AddVoice("INFECTION", "Infection.", "I have a 10-30 at my 10-20, respond code 2")
AddVoice("INFESTEDZONE", "Infested Zone.", "npc/metropolice/vo/infestedzone.wav")
AddVoice("INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
AddVoice("INNOCULATE", "Innoculate.", "npc/metropolice/vo/innoculate.wav")
AddVoice("INPOSITION", "In position.", "npc/metropolice/vo/inposition.wav")
AddVoice("INPOSITIONHARDPOINT", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
AddVoice("INTERCEDE", "Intercede.", "npc/metropolice/vo/intercede.wav")
AddVoice("INTERLOCK", "Interlock.", "npc/metropolice/vo/interlock.wav")
AddVoice("INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
AddVoice("INVESTIGATE10-103", "Investgating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
AddVoice("IS10-108", "is 10-108", "npc/metropolice/vo/is10-108.wav")
AddVoice("IS415B", "is 415B", "npc/metropolice/vo/is415b.wav")
AddVoice("SAIDMOVEALONG", "I said move along!", "npc/metropolice/vo/isaidmovealong.wav")
AddVoice("ATHARDPOINTREADYTOPROSECUTE", "is at hardpoint, ready to prosecute!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
AddVoice("CLOSINGONSUSPECT", "is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav")
AddVoice("ISDOWN", "is down!", "npc/metropolice/vo/isdown.wav")
AddVoice("ISMOVINGIN", "is moving in!", "npc/metropolice/vo/ismovingin.wav")
AddVoice("ISOLATE", "Isolate.", "npc/metropolice/vo/isolate.wav")
AddVoice("ISPASSIVE", "is passive.", "npc/metropolice/vo/ispassive.wav")
AddVoice("MALCOPLIANTCITATION", "Issuing malcopliant citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
AddVoice("408HERE", "I've got a 408 here at location.", "npc/metropolice/vo/ivegot408hereatlocation.wav")
AddVoice("JURY", "Jury!", "npc/metropolice/vo/jury.wav")
AddVoice("KEEPMOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
AddVoice("KING", "King!", "npc/metropolice/vo/king.wav")
AddVoice("LEVEL3PRIVACY", "Level 3 civil privacy violator.", "npc/metropolice/vo/level3civilprivacyviolator.wav")
AddVoice("LINE", "Line!", "npc/metropolice/vo/line.wav")
AddVoice("CPREPORTSTATUS", "Local CPT, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
AddVoice("LOCATION", "Location.", "npc/metropolice/vo/location.wav")
AddVoice("LOCK", "Lock.", "npc/metropolice/vo/lock.wav")
AddVoice("LOCKPOSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
AddVoice("LOOKINGTROUBLE", "Looking for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
AddVoice("LOOKOUT", "Look out!", "npc/metropolice/vo/lookout.wav")
AddVoice("MALCOPLIANT10-107", "Malcopliant 10-107 at my 10-20, ready to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
AddVoice("MALIGNANT", "Malignant.", "npc/metropolice/vo/malignant.wav")
AddVoice("MOVE", "Move.", "npc/metropolice/vo/move.wav")
AddVoice("MOVEALONG", "Move along.", "npc/metropolice/vo/movealong.wav")
AddVoice("MOVEBACK", "Move back right now!", "npc/metropolice/vo/movebackrightnow.wav")
AddVoice("MOVEIT", "Move it.", "npc/metropolice/vo/moveit2.wav")
AddVoice("MOVEIT2", "Move it!", "npc/metropolice/vo/moveit.wav")
AddVoice("MOVEARRESTPOSITIONS", "All units, move to arrest positions.", "npc/metropolice/vo/movetoarrestpositions.wav")
AddVoice("MOVINGTOCOVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
AddVoice("NECROTICS", "Necrotics!", "npc/metropolice/vo/necrotics.wav")
AddVoice("HELPWITHTHISONE", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
AddVoice("9", "Nine.", "npc/metropolice/vo/nine.wav")
AddVoice("19", "Nineteen", "npc/metropolice/vo/nineteen.wav")
AddVoice("90", "Ninety", "npc/metropolice/vo/ninety.wav")
AddVoice("NOCONTACT", "No contact.", "npc/metropolice/vo/nocontact.wav")
AddVoice("NONCITIZEN", "Non-Citizen", "npc/metropolice/vo/noncitizen.wav")
AddVoice("NONPATROLREGION", "Non-Patrol Region", "npc/metropolice/vo/nonpatrolregion.wav")
AddVoice("NOVISUALONUPI", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
AddVoice("NOWGETOUT", "Now, get out of here.", "npc/metropolice/vo/nowgetoutofhere.wav")
AddVoice("OFFICERDOWN", "Officer down, request all units code 3 to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
AddVoice("OFFICERDOWN10-99", "Officer down, I am 10-99, I repeat I am 10-99!", "npc/metropolice/vo/officerdowniam10-99.wav")
AddVoice("OFFICERASSISTANCE", "Officer needs assitance, I'm 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
AddVoice("OFFICERHELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
AddVoice("OFFICERFIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
AddVoice("100", "One hundred", "npc/metropolice/vo/onehundred.wav")
AddVoice("OUTBREAK", "Outbreak!", "npc/metropolice/vo/outbreak.wav")

Schema.voices.AddClass("CivilProtection", function(ply)
	return Schema:IsCP(ply)
end)