local citizenFemaleVCs = {
    {"HELP ME", "Help me!", "vo/canals/arrest_helpme.wav"},
    {"GET GOING NOW", "You'd better get going now.", "vo/canals/airboat_go_nag01.wav"},
    {"YOU GO ON", "I'm staying put. You go on.", "vo/canals/airboat_go_nag03.wav"},
    {"GET GOING", "Get going!", "vo/canals/arrest_getgoing.wav"},
    {"LOOKING FOR YOU", "They'll be looking for you now.", "vo/canals/arrest_lookingforyou.wav"},
    {"NOTHING YOU CAN DO", "You better run, there's nothing else you can do here.", "vo/canals/arrest_run.wav"},
    {"DIDN'T DO ANYTHING", "Stop! We didn't do anything!", "vo/canals/arrest_stop.wav"},
    {"GO ON", "Go on!", "vo/canals/female01/stn6_go_nag02.wav"},
    {"INCOMING", "Incoming!", "vo/canals/female01/stn6_incoming.wav"},
    {"THEYRE SHELLING US", "They're shelling us!", "vo/canals/female01/stn6_shellingus.wav"},
    {"HERE COME THE DROPSHIPS", "Oh crap! Here come the dropships!", "vo/coast/barn/female01/crapships.wav"},
    {"OFF THE ROAD", "Get off the road!", "vo/coast/barn/female01/getoffroad01.wav"},
    {"INCOMING DROPSHIP", "Incoming dropship!", "vo/coast/barn/female01/incomingdropship.wav"},
    {"GUNSHIP", "It's a gunship!", "vo/coast/barn/female01/lite_gunship01.wav"},
    {"GUNSHIP2", "Gunship!", "vo/coast/barn/female01/lite_gunship02.wav"},
    {"YOU MADE IT", "You made it!", "vo/coast/barn/female01/youmadeit.wav"},
    {"CHEER", "*Cheering.*", "vo/coast/odessa/female01/nlo_cheer01.wav"},
    {"CHEER2", "*Cheering.*", "vo/coast/odessa/female01/nlo_cheer02.wav"},
    {"CHEER3", "*Cheering.*", "vo/coast/odessa/female01/nlo_cheer03.wav"},
    {"DRIVE SAFELY", "Drive safely.", "vo/coast/odessa/female01/nlo_citizen_drivesafe.wav"},
    {"NOO", "No, Nooo!", "vo/coast/odessa/female01/nlo_cubdeath01.wav"},
    {"NOO2", "Nooo!", "vo/coast/odessa/female01/nlo_cubdeath02.wav"},
    {"THIS WAY", "This way.", "vo/coast/odessa/female01/stairman_follow01.wav"},
    {"AMMO", "Here, ammo!", "vo/npc/female01/ammo03.wav"},
    {"AMMO2", "Take some ammo!", "vo/npc/female01/ammo04.wav"},
    {"AMMO3", "Take some ammo!", "vo/npc/female01/ammo05.wav"},
    {"YOU ALL OVER", "That's you all over.", "vo/npc/female01/answer01.wav"},
    {"WONT HOLD IT AGAINST", "I wont hold it against you.", "vo/npc/female01/answer02.wav"},
    {"FIGURES", "Figures.", "vo/npc/female01/answer03.wav"},
    {"TRY NOT TO DWELL", "Try not to dwell on it.", "vo/npc/female01/answer04.wav"},
    {"CANWETALKLATER", "Can we talk about this later?", "vo/npc/female01/answer05.wav"},
    {"SAMEHERE", "Same here.", "vo/npc/female01/answer07.wav"},
    {"KNOW WHAT YOU MEAN", "Know what you mean.", "vo/npc/female01/answer08.wav"},
    {"TALKING TO YOURSELF", "You're taking to yourself again.", "vo/npc/female01/answer09.wav"},
    {"WOULDNT SAY TOO LOUD", "I wouldn't say that too loud.", "vo/npc/female01/answer10.wav"},
    {"TOMB STONE", "I'll put it on your tombstone.", "vo/npc/female01/answer11.wav"},
    {"BEAR THINKING ABOUT", "Doesn't bear thinking about.", "vo/npc/female01/answer12.wav"},
    {"IM WITH YOU", "I'm with you.", "vo/npc/female01/answer13.wav"},
    {"YOU AND ME BOTH", "You and me both.", "vo/npc/female01/answer14.wav"},
    {"ONE WAY", "That's... one way of looking at it.", "vo/npc/female01/answer15.wav"},
    {"ORIGINAL THOUGHT", "Have you ever had an original thought?", "vo/npc/female01/answer16.wav"},
    {"SHUT UP", "I'm not even gonna tell you to shut up.", "vo/npc/female01/answer17.wav"},
    {"CONCENTRATE", "Let's concentrate on the task at hand.", "vo/npc/female01/answer18.wav"},
    {"MIND ON YOUR WORK", "Keep your mind on your work.", "vo/npc/female01/answer19.wav"},
    {"IN THE GUTTER", "Your mind is in the gutter.", "vo/npc/female01/answer20.wav"},
    {"DON'T BE SO SURE", "Don't be so sure of that.", "vo/npc/female01/answer21.wav"},
    {"YOU NEVER KNOW", "You never know.", "vo/npc/female01/answer22.wav"},
    {"NEVER CAN'T TELL", "Never can't tell.", "vo/npc/female01/answer23.wav"},
    {"TELLING ME", "Why are you telling me?", "vo/npc/female01/answer24.wav"},
    {"HOW ABOUT THAT", "How about that.", "vo/npc/female01/answer25.wav"},
    {"MORE INFORMATION", "That's more information than I require.", "vo/npc/female01/answer26.wav"},
    {"WANNA BET", "Wanna bet?", "vo/npc/female01/answer27.wav"},
    {"WISH I HAD A DIME", "I wish I had a dime for every time somebody said that.", "vo/npc/female01/answer28.wav"},
    {"WHAT AM I SUPPOSED TO DO", "What am I supposed to do about it?", "vo/npc/female01/answer29.wav"},
    {"TALKING TO ME", "You talking to me?", "vo/npc/female01/answer30.wav"},
    {"NIP THAT TALK", "You should nip that kind of talk in the bud.", "vo/npc/female01/answer31.wav"},
    {"RIGHT ON", "Right on.", "vo/npc/female01/answer32.wav"},
    {"NO ARGUMENT", "No argument there.", "vo/npc/female01/answer33.wav"},
    {"DON'T FORGET HAWAII", "Don't forget Hawaii", "vo/npc/female01/answer34.wav"},
    {"DON'T LET IT GET TO YOU", "Try not to let it get to you.", "vo/npc/female01/answer35.wav"},
    {"FIRST TIME", "Wouldn't be the first time.", "vo/npc/female01/answer36.wav"},
    {"SURE ABOUT THAT", "You sure about that?", "vo/npc/female01/answer37.wav"},
    {"LEAVE IT", "Leave it alone.", "vo/npc/female01/answer38.wav"},
    {"ENOUGH OUTTA YOU", "That's enough outta you.", "vo/npc/female01/answer39.wav"},
    {"FIRST TIME FOR EVERYTHING", "There's a first time for everything.", "vo/npc/female01/answer40.wav"},
    {"BEHIND YOU", "Behind you!", "vo/npc/female01/behindyou01.wav"},
    {"BEHIND YOU2", "Behind you!", "vo/npc/female01/behindyou02.wav"},
    {"IM BUSY", "Can't you see I'm busy?", "vo/npc/female01/busy02.wav"},
    {"SUPPLIES", "Hey down there! Supplies!", "vo/npc/female01/cit_dropper01.wav"},
    {"LOOK OUT BELOW", "Look out below!", "vo/npc/female01/cit_dropper04.wav"},
    {"CIVIL PROTECTION", "Civil Protection!", "vo/npc/female01/civilprotection01.wav"},
    {"CIVIL PROTECTION2", "Civil Protection!", "vo/npc/female01/civilprotection02.wav"},
    {"COMBINE", "Combine!", "vo/npc/female01/combine01.wav"},
    {"COMBINE2", "Combine!", "vo/npc/female01/combine02.wav"},
    {"RELOADING", "Cover me while I reload!", "vo/npc/female01/coverwhilereload01.wav"},
    {"RELOADING2", "Cover me while I reload!", "vo/npc/female01/coverwhilereload02.wav"},
    {"CPS", "CPs!", "vo/npc/female01/cps01.wav"},
    {"CPS2", "CPs!", "vo/npc/female01/cps02.wav"},
    {"DOING SOMETHING", "Shouldn't we be doing something?", "vo/npc/female01/doingsomething.wav"},
    {"EXCUSE ME", "Excuse me.", "vo/npc/female01/excuseme01.wav"},
    {"EXCUSE ME2", "Excuse me.", "vo/npc/female01/excuseme02.wav"},
    {"FANTASTIC", "Fantastic.", "vo/npc/female01/fantastic01.wav"},
    {"FANTASTIC2", "Fantastic.", "vo/npc/female01/fantastic02.wav"},
    {"FINALLY", "Finally.", "vo/npc/female01/finally.wav"},
    {"GET DOWN", "Get down!", "vo/npc/female01/getdown02.wav"},
    {"GET GOING SOON", "Are we gonna get going soon?", "vo/npc/female01/getgoingsoon.wav"},
    {"GET THE HELL OUTTA HERE", "Get the hell outta here!", "vo/npc/female01/gethellout.wav"},
    {"GOOD GOD", "Good god!", "vo/npc/female01/goodgod.wav"},
    {"NOW WHAT", "Now what?", "vo/npc/female01/gordead_ans01.wav"},
    {"GOING SOWELL", "And things were going so well.", "vo/npc/female01/gordead_ans02.wav"},
    {"DON'T TELL ME", "Don't tell me.", "vo/npc/female01/gordead_ans03.wav"},
    {"OH GOD", "Oh God.", "vo/npc/female01/gordead_ans04.wav"},
    {"OH NO", "Oh no.", "vo/npc/female01/gordead_ans05.wav"},
    {"PLEASE NO", "Please, no.", "vo/npc/female01/gordead_ans06.wav"},
    {"IF YOU DARE SAY", "If you dare say 'That's gotta hurt', I'll kill you.", "vo/npc/female01/gordead_ans07.wav"},
    {"SHOULD WE BURY HIM", "Should we bury him here?", "vo/npc/female01/gordead_ans08.wav"},
    {"SPREAD THE WORD", "Spread the word.", "vo/npc/female01/gordead_ans10.wav"},
    {"WHATS THE USE", "What's the use?", "vo/npc/female01/gordead_ans11.wav"},
    {"WHATS THE POINT", "What's the point?", "vo/npc/female01/gordead_ans12.wav"},
    {"WHY GO ON", "Why go on?", "vo/npc/female01/gordead_ans13.wav"},
    {"WERE DONE FOR", "We're done for.", "vo/npc/female01/gordead_ans14.wav"},
    {"NOW WHAT2", "Well, now what?", "vo/npc/female01/gordead_ans15.wav"},
    {"DONE THIS BEFORE", "He's done this before, he'll be ok.", "vo/npc/female01/gordead_ans18.wav"},
    {"IM GONNA BE SICK", "I'm gonna be sick.", "vo/npc/female01/gordead_ans19.wav"},
    {"HES DEAD", "He's dead.", "vo/npc/female01/gordead_ques01.wav"},
    {"WAY TO GO", "What a way to go.", "vo/npc/female01/gordead_ques02.wav"},
    {"THIS CAN'T BE", "This can't be.", "vo/npc/female01/gordead_ques06.wav"},
    {"HES DEAD2", "Look, he's dead!", "vo/npc/female01/gordead_ques07.wav"},
    {"THIS IS BAD", "This is bad.", "vo/npc/female01/gordead_ques10.wav"},
    {"NOT SUPPOSED TO END", "It's not supposed to end like this!", "vo/npc/female01/gordead_ques14.wav"},
    {"WHAT NOW", "What now?", "vo/npc/female01/gordead_ques16.wav"},
    {"GOT ONE", "Got one!", "vo/npc/female01/gotone01.wav"},
    {"GOT ONE2", "I got one!", "vo/npc/female01/gotone02.wav"},
    {"RELOADING3", "Gotta reload.", "vo/npc/female01/gottareload01.wav"},
    {"GUNSHIP3", "Gunship!", "vo/npc/female01/gunship02.wav"},
    {"HEADCRABS", "Headcrabs!", "vo/npc/female01/headcrabs01.wav"},
    {"HEADCRABS2", "Headcrabs!", "vo/npc/female01/headcrabs02.wav"},
    {"HEADSUP", "Heads up!", "vo/npc/female01/headsup01.wav"},
    {"HEADSUP2", "Heads up!", "vo/npc/female01/headsup02.wav"},
    {"MEDKIT", "Take this medkit.", "vo/npc/female01/health01.wav"},
    {"MEDKIT2", "Take this medkit.", "vo/npc/female01/health02.wav"},
    {"MEDKIT3", "Take this medkit.", "vo/npc/female01/health03.wav"},
    {"MEDKIT4", "Here, have a medkit.", "vo/npc/female01/health04.wav"},
    {"MEDKIT5", "Here, patch yourself up.", "vo/npc/female01/health05.wav"},
    {"HELP", "Help!", "vo/npc/female01/help01.wav"},
    {"HERE COME THE HACKS", "Here come the hacks!", "vo/npc/female01/herecomehacks01.wav"},
    {"HERE COME THE HACKS2", "Here come the hacks!", "vo/npc/female01/herecomehacks02.wav"},
    {"HERE THEY COME", "Here they come!", "vo/npc/female01/heretheycome01.wav"},
    {"HI", "Hi.", "vo/npc/female01/hi01.wav"},
    {"HI2", "Hi.", "vo/npc/female01/hi02.wav"},
    {"HIT IN THE GUT", "Hit in the gut.", "vo/npc/female01/hitingut01.wav"},
    {"HIT IN THE GUT2", "Hit in the gut.", "vo/npc/female01/hitingut02.wav"},
    {"HOLD DOWN THIS SPOT", "I'm gonna stay and hold down this spot.", "vo/npc/female01/holddownspot01.wav"},
    {"HOLD DOWN THIS SPOT2", "I'm gonna stay and hold down this spot.", "vo/npc/female01/holddownspot02.wav"},
    {"ILL STAY HERE", "I'll stay here.", "vo/npc/female01/illstayhere01.wav"},
    {"IM HURT", "I'm hurt.", "vo/npc/female01/imhurt01.wav"},
    {"IM HURT2", "I'm hurt.", "vo/npc/female01/imhurt02.wav"},
    {"IM STICKING HERE", "I'm sticking here.", "vo/npc/female01/imstickinghere01.wav"},
    {"INCOMING2", "Incoming!", "vo/npc/female01/incoming02.wav"},
    {"ITS A MANHACK", "It's a manhack!", "vo/npc/female01/itsamanhack01.wav"},
    {"ITS A MANKACK2", "It's a manhack!", "vo/npc/female01/itsamanhack02.wav"},
    {"LEAD THE WAY", "You lead the way!", "vo/npc/female01/leadtheway01.wav"},
    {"LEAD THE WAY2", "Lead the way!", "vo/npc/female01/leadtheway02.wav"},
    {"LETS GO", "Let's go!", "vo/npc/female01/letsgo01.wav"},
    {"LETS GO2", "Let's go!", "vo/npc/female01/letsgo02.wav"},
    {"LIKE THAT", "Like that?!", "vo/npc/female01/likethat.wav"},
    {"CORNER", "I've got my little corner and I'm sticking to it.", "vo/npc/female01/littlecorner01.wav"},
    {"GROAN", "*Groan.*", "vo/npc/female01/moan01.wav"},
    {"GROAN2", "*Groan.*", "vo/npc/female01/moan02.wav"},
    {"GROAN3", "*Groan.*", "vo/npc/female01/moan03.wav"},
    {"GROAN4", "*Groan.*", "vo/npc/female01/moan04.wav"},
    {"GROAN5", "*Groan.*", "vo/npc/female01/moan05.wav"},
    {"MY ARM", "My arm.", "vo/npc/female01/myarm01.wav"},
    {"MY ARM2", "My arm.", "vo/npc/female01/myarm02.wav"},
    {"MY GUT", "My gut.", "vo/npc/female01/mygut02.wav"},
    {"MY LEG", "My leg.", "vo/npc/female01/myleg01.wav"},
    {"MY LEG2", "My leg.", "vo/npc/female01/myleg02.wav"},
    {"NICE", "Nice.", "vo/npc/female01/nice.wav"},
    {"OH NO2", "Oh no.", "vo/npc/female01/ohno.wav"},
    {"OK", "Ok.", "vo/npc/female01/ok01.wav"},
    {"OK2", "Ok.", "vo/npc/female01/ok02.wav"},
    {"OK IM READY", "Ok, I'm ready.", "vo/npc/female01/okimready01.wav"},
    {"OK IM READY2", "Ok, I'm ready.", "vo/npc/female01/okimready02.wav"},
    {"OK IM READY3", "Ok, I'm ready!", "vo/npc/female01/okimready03.wav"},
    {"ONE FOR ME", "One for me and one for me.", "vo/npc/female01/oneforme.wav"},
    {"OUT OF YOUR WAY", "Let me get out of your way.", "vo/npc/female01/outofyourway02.wav"},
    {"HEY OVER HERE", "Hey over here!", "vo/npc/female01/overhere01.wav"},
    {"OVER THERE", "Over there!", "vo/npc/female01/overthere01.wav"},
    {"OVER THERE2", "Over there!", "vo/npc/female01/overthere02.wav"},
    {"OW", "Ow!", "vo/npc/female01/ow01.wav"},
    {"OW2", "Ow!", "vo/npc/female01/ow02.wav"},
    {"PARDON ME", "Pardon me.", "vo/npc/female01/pardonme01.wav"},
    {"PARDON ME2", "Pardon me.", "vo/npc/female01/pardonme02.wav"},
    {"EVER GONNA END", "I don't think this war is ever gonna end.", "vo/npc/female01/question01.wav"},
    {"INSURANCE", "To think, all I used to want to do was sell insurance.", "vo/npc/female01/question02.wav"},
    {"DON'T DREAM", "I don't dream anymore.", "vo/npc/female01/question03.wav"},
    {"WHEN THIS IS OVER", "When this is all over I'm...aw, who am I kidding?", "vo/npc/female01/question04.wav"},
    {"DEJAVU", "Woah, Deja vu.", "vo/npc/female01/question05.wav"},
    {"CHEESE", "Sometimes, I dream about cheese.", "vo/npc/female01/question06.wav"},
    {"FREEDOM", "You semm that? It's freedom!", "vo/npc/female01/question07.wav"},
    {"EAT A HORSE", "I could eat a horse, hooves and all.", "vo/npc/female01/question09.wav"},
    {"CAN'T BELIEVE THIS DAY", "I can't believe this day has finally come!", "vo/npc/female01/question10.wav"},
    {"NOT PART OF PLAN", "I'm pretty sure this isn't part of the plan.", "vo/npc/female01/question11.wav"},
    {"WORSE NOT BETTER", "Looks to me things are getting worse, not better.", "vo/npc/female01/question12.wav"},
    {"LIVE MY LIFE ALL OVER", "If I could live my life all over again.", "vo/npc/female01/question13.wav"},
    {"WHAT THAT REMINDS ME", "I'm not even gonna tell you what that reminds me of.", "vo/npc/female01/question14.wav"},
    {"STALKER OUT OF ME", "They're never gonna make a stalker out of me.", "vo/npc/female01/question15.wav"},
    {"CHANGE IS IN THE AIR", "Finally, change is in the air!", "vo/npc/female01/question16.wav"},
    {"YOU FEEL IT", "You feel it? I feel it!", "vo/npc/female01/question17.wav"},
    {"DON'T FEEL ANYTHING", "I don't feel anything anymore.", "vo/npc/female01/question18.wav"},
    {"SHOWER", "I can't remember the last time I had a shower.", "vo/npc/female01/question19.wav"},
    {"BAD MEMORY", "Some day, this will all be a bad memory.", "vo/npc/female01/question20.wav"},
    {"BETTING", "I'm not a betting man, but the odds are not good.", "vo/npc/female01/question21.wav"},
    {"CARE WHAT I THINK", "Doesn't anyone care what I think?", "vo/npc/female01/question22.wav"},
    {"TUNE", "I can't get this tune out of my head. *Whistling.*", "vo/npc/female01/question23.wav"},
    {"ONE OF THOSE DAYS", "I just knew it was gonna be one of those days.", "vo/npc/female01/question25.wav"},
    {"BULLSHIT", "This is bullshit.", "vo/npc/female01/question26.wav"},
    {"ATE SOMETHING BAD", "I think I ate something bad.", "vo/npc/female01/question27.wav"},
    {"HUNGRY", "God, I'm hungry.", "vo/npc/female01/question28.wav"},
    {"IM GONNA MATE", "When this is all over, I'm gonna mate.", "vo/npc/female01/question29.wav"},
    {"NO KIDS", "I'm glad there's no kids around to see this.", "vo/npc/female01/question30.wav"},
    {"READY WHEN YOU ARE", "Ready when you are!", "vo/npc/female01/readywhenyouare01.wav"},
    {"READY WHEN YOU ARE2", "Ready when you are!", "vo/npc/female01/readywhenyouare02.wav"},
    {"RUN FOR YOUR LIFE", "Run for your life!", "vo/npc/female01/runforyourlife01.wav"},
    {"RUN FOR YOUR LIFE2", "Run for your life!", "vo/npc/female01/runforyourlife02.wav"},
    {"RUN FOR YOUR LIFE3", "Run for your life!", "vo/npc/female01/runforyourlife03.wav"},
    {"SCANNERS", "Scanners!", "vo/npc/female01/scanners01.wav"},
    {"SCANNERS2", "Scanners!", "vo/npc/female01/scanners02.wav"},
    {"SORRY", "Sorry.", "vo/npc/female01/sorry01.wav"},
    {"SORRY2", "Sorry.", "vo/npc/female01/sorry02.wav"},
    {"SORRY3", "Sorry.", "vo/npc/female01/sorry03.wav"},
    {"WHAT EVER YOU SAY", "Whatever you say.", "vo/npc/female01/squad_affirm03.wav"},
    {"OK IM GOING", "Ok, I'm going.", "vo/npc/female01/squad_affirm04.wav"},
    {"HERE GOES", "Here goes.", "vo/npc/female01/squad_affirm05.wav"},
    {"HERE GOES NOTHING", "Here goes nothing.", "vo/npc/female01/squad_affirm06.wav"},
    {"HERE WE COME", "Here we come!", "vo/npc/female01/squad_approach02.wav"},
    {"ON OUR WAY", "On our way!", "vo/npc/female01/squad_approach03.wav"},
    {"COMING", "Coming!", "vo/npc/female01/squad_approach04.wav"},
    {"THIS WAY GANG", "This way gang!", "vo/npc/female01/squad_away01.wav"},
    {"OVER HERE", "Over here!", "vo/npc/female01/squad_away02.wav"},
    {"FOLLOW ME", "Follow me!", "vo/npc/female01/squad_away03.wav"},
    {"COME ON EVERY BODY", "Come on everybody!", "vo/npc/female01/squad_follow02.wav"},
    {"LETS GET MOVING", "Let's get moving.", "vo/npc/female01/squad_follow03.wav"},
    {"WAIT FOR US", "Wait for us!", "vo/npc/female01/squad_reinforce_group04.wav"},
    {"WAIT FOR ME", "Wait for me!", "vo/npc/female01/squad_reinforce_single04.wav"},
    {"GASP", "*Gasp.*", "vo/npc/female01/startle01.wav"},
    {"GASP2", "*Gasp.*", "vo/npc/female01/startle02.wav"},
    {"STRIDER", "Strider!", "vo/npc/female01/strider.wav"},
    {"RUN", "Run!", "vo/npc/female01/strider_run.wav"},
    {"TAKE COVER", "Take cover!", "vo/npc/female01/takecover02.wav"},
    {"THIS WILL DO NICELY", "This will do nicely.", "vo/npc/female01/thislldonicely01.wav"},
    {"UH OH", "Uh oh.", "vo/npc/female01/uhoh.wav"},
    {"UP THERE", "Up there!", "vo/npc/female01/upthere01.wav"},
    {"UP THERE2", "Up there!", "vo/npc/female01/upthere02.wav"},
    {"MUMBOJUMBO", "Enough of your mumbo jumbo.", "vo/npc/female01/vanswer01.wav"},
    {"DAMN VORTS", "Damn vorts.", "vo/npc/female01/vanswer02.wav"},
    {"NOT SURE HOW TO TAKE THAT", "I'm not sure how to take that.", "vo/npc/female01/vanswer03.wav"},
    {"TAKE THAT PERSONALLY", "Should I take that personally?", "vo/npc/female01/vanswer04.wav"},
    {"SPEAK ENGLISH", "Speak English.", "vo/npc/female01/vanswer05.wav"},
    {"GOT FROM ME", "You got that from me.", "vo/npc/female01/vanswer06.wav"},
    {"WE PUT UP WITH YOU", "That's why we put up with you.", "vo/npc/female01/vanswer07.wav"},
    {"PUT IT BETTER MYSELF", "Couldn't have put it better myself.", "vo/npc/female01/vanswer08.wav"},
    {"ALMOST MADE SENSE", "That... almost made sense.", "vo/npc/female01/vanswer09.wav"},
    {"ALMOST UNDERSTOOD", "Something must be wrong with me, I almost understood that.", "vo/npc/female01/vanswer10.wav"},
    {"GETTING USED TO VORTS", "I guess I'm getting used to you vorts.", "vo/npc/female01/vanswer11.wav"},
    {"VORT PHILOSOPHY", "None of your vort philosoply.", "vo/npc/female01/vanswer12.wav"},
    {"KILLING ME", "Stop, you're killing me.", "vo/npc/female01/vanswer13.wav"},
    {"DESERVE THIS", "What did I do to deserve this?", "vo/npc/female01/vanswer14.wav"},
    {"STOP LOOKING", "Stop looking at me like that.", "vo/npc/female01/vquestion01.wav"},
    {"NEVER GET USED TO", "Some things I just never get used to.", "vo/npc/female01/vquestion02.wav"},
    {"HOW YOU THINGS", "I don't know how you things have survived as long as you have.", "vo/npc/female01/vquestion03.wav"},
    {"HOW I ENDED UP", "Sometimes I wonder how I ended up with you.", "vo/npc/female01/vquestion04.wav"},
    {"YOURE ALRIGHT VORTY", "You're all right vorty.", "vo/npc/female01/vquestion05.wav"},
    {"VORTS ARENT HALF BAD", "You vorts aren't half bad.", "vo/npc/female01/vquestion06.wav"},
    {"PALS WITH A VORT", "If anyone would have told me I'd be pals with a vortigaunt...", "vo/npc/female01/vquestion07.wav"},
    {"WAITING FOR SOMEBODY", "You waiting for somebody?", "vo/npc/female01/waitingsomebody.wav"},
    {"WATCH OUT", "Watch out!", "vo/npc/female01/watchout.wav"},
    {"WHATCH WHAT YOURE DOING", "Watch what you're doing!", "vo/npc/female01/watchwhat.wav"},
    {"WE TRUSTED YOU", "We trusted you!", "vo/npc/female01/wetrustedyou01.wav"},
    {"WE TRUSTED YOU2", "We trusted you!", "vo/npc/female01/wetrustedyou02.wav"},
    {"WHOOPS", "Whoops.", "vo/npc/female01/whoops01.wav"},
    {"YEAH", "Yeah.", "vo/npc/female01/yeah02.wav"},
    {"BETTERR ELOAD", "You better reload.", "vo/npc/female01/youdbetterreload01.wav"},
    {"YOU GOT IT", "You got it.", "vo/npc/female01/yougotit02.wav"},
    {"ZOMBIES", "Zombies!", "vo/npc/female01/zombies01.wav"},
    {"ZOMBIES2", "Zombies!", "vo/npc/female01/zombies02.wav"},
    {"HOPPERS", "Watch out for the hoppers! They're everywhere!", "vo/streetwar/barricade/female01/c17_05_hoppers.wav"},
    {"LETUSTHROUGH", "Let us through!", "vo/streetwar/barricade/female01/c17_05_letusthru.wav"},
    {"OPENTHEGATE", "Open the gate!", "vo/streetwar/barricade/female01/c17_05_opengate.wav"},
    {"LETUSOUT", "Hey! Let us out of here!", "vo/streetwar/nexus/female01/c17_10_letusout.wav"},
    {"HORSE", "Head for the horse!", "vo/streetwar/rubble/female01/d3_c17_13_horse01.wav"},
    {"HORSE2", "We have to get to the horse!", "vo/streetwar/rubble/female01/d3_c17_13_horse02.wav"},
    {"ALMOSTDONE", "If you can hold them off, I'm almost done here!", "vo/streetwar/tunnel/female01/c17_06_det02.wav"},
    {"LASTCHARGE", "Ok, last charge!", "vo/streetwar/tunnel/female01/c17_06_det03.wav"},
    {"ITSGONNABLOW", "Stand back! It's gonna blow!", "vo/streetwar/tunnel/female01/c17_06_det04.wav"},
    {"OPENTHEDOOR", "Hey, It's me. Open the door.", "vo/streetwar/tunnel/female01/c17_06_password01.wav"},
    {"PASSWORD", "What's the password?", "vo/streetwar/tunnel/female01/c17_06_password02.wav"},
    {"COMEONIN", "Come on in.", "vo/streetwar/tunnel/female01/c17_06_password04.wav"},
    {"COMEACROSS", "Ok, come across.", "vo/streetwar/tunnel/female01/c17_06_plank01.wav"},
    {"COMEACROSS2", "I've got to stay here in case anyone else needs to get across.", "vo/streetwar/tunnel/female01/c17_06_plank02.wav"},
    {"MADEITTHROUGH", "I see you made it through okay. Figured you would.", "vo/streetwar/tunnel/female01/d3_c17_06_post_det04.wav"},
    {"ONLY ONES", "Were you the only ones on that train?", "vo/trainyard/cit_fence_onlyones.wav"},
    {"ONE OF US", "He's one of us.", "vo/trainyard/cit_window_stand.wav"},
    {"COMING FOR US NEXT", "I told you they'd be coming for us next.", "vo/trainyard/cit_window_usnext.wav"},
    {"CAN'T TAKE IT", "I can't take it anymore.", "vo/trainyard/wife_canttake.wav"},
    {"ALLGOINGTOEND", "When is it all going to end?", "vo/trainyard/wife_end.wav"},
    {"PLEASE", "Please.", "vo/trainyard/wife_please.wav"},
    {"GOING TO DO", "What are we going to do?", "vo/trainyard/wife_whattodo.wav"},
    {"STAY BACK", "Stay back, you;ll sttract unwanted attention", "vo/trainyard/female01/cit_bench01.wav"},
    {"CAN'T BE SEEN", "I can't be seen talking to you, not out here.", "vo/trainyard/female01/cit_bench02.wav"},
    {"DON'T SIT", "Don't sit near me, it'll look suspicious.", "vo/trainyard/female01/cit_bench03.wav"},
    {"PIGEONS", "You're scaring off the pigeons.", "vo/trainyard/female01/cit_bench04.wav"},
    {"LINE", "The line starts at the end.", "vo/trainyard/female01/cit_foodline01.wav"},
    {"WAIT YOUR TURN", "You'll have to wait your turn like everybody else.", "vo/trainyard/female01/cit_foodline02.wav"},
    {"DAMN HUNGRY", "You gotta be damn hungry to wait in line for this crap.", "vo/trainyard/female01/cit_foodline03.wav"},
    {"JOIN CP", "I don't know about you, but I'm ready to join Civil Protection just to get a decent meal.", "vo/trainyard/female01/cit_foodline04.wav"},
    {"CUT IT OUT", "Cut it out!", "vo/trainyard/female01/cit_hit01.wav"},
    {"STOP THAT", "Stop that!", "vo/trainyard/female01/cit_hit02.wav"},
    {"WATCH IT WILL YOU", "Watch it will you?", "vo/trainyard/female01/cit_hit03.wav"},
    {"NO MORE", "No more.", "vo/trainyard/female01/cit_hit04.wav"},
    {"ENOUGH OF THAT", "That's enough of that!", "vo/trainyard/female01/cit_hit05.wav"},
    {"NEW IN TOWN", "New in town, aren't you?", "vo/trainyard/female01/cit_pedestrian01.wav"},
    {"KEEP IT TO YOU", "Word to the wise, keep it to youself.", "vo/trainyard/female01/cit_pedestrian02.wav"},
    {"BOTH BE IN TROUBLE", "If I talk to you out here, we'll both be in trouble.", "vo/trainyard/female01/cit_pedestrian03.wav"},
    {"CAN'T BE SEEN2", "We can't be seen talking to each other.", "vo/trainyard/female01/cit_pedestrian04.wav"},
    {"LIKE TO HELP YOU", "I'd like to help you, but it's out of the question.", "vo/trainyard/female01/cit_pedestrian05.wav"},
    {"SOMEONE HAD COURAGE", "Thank God someone had the courage to do that.", "vo/trainyard/female01/cit_tvbust05.wav"},
    {"DOESNT LOOK GOOD", "This doesn't look good.", "vo/trainyard/female01/cit_window_use01.wav"},
    {"COMING IN HERE", "They're definitely coming in here.", "vo/trainyard/female01/cit_window_use02.wav"},
    {"MATTER OF TIME", "It was just a matter of time.", "vo/trainyard/female01/cit_window_use03.wav"},
    {"NEIGHBORHOOD", "Here goes the rest of the neighborhood.", "vo/trainyard/female01/cit_window_use04.wav"},
    {"CRY1", "*Cries*", "ambient/creatures/town_scared_breathing1.wav"},
    {"CRY2", "*Cries*", "ambient/creatures/town_scared_breathing2.wav"},
    {"COUGH1", "*Coughs*", "ambient/voices/cough1.wav"},
    {"COUGH2", "*Coughs*", "ambient/voices/cough2.wav"},
    {"COUGH3", "*Coughs*", "ambient/voices/cough3.wav"},
    {"COUGH4", "*Coughs*", "ambient/voices/cough4.wav"},
}

for k, v in ipairs(citizenFemaleVCs) do
    Schema.voices.Add("CitizenFemale", v[1], v[2], v[3])
end

Schema.voices.AddClass("CitizenFemale", function(ply)
    return Schema:IsCitizen(ply) and ply:IsFemale()
end)