local cpVoicelines = {
    {"0", "Zero", "npc/metropolice/vo/zero.wav"},
    {"10", "Ten", "npc/metropolice/vo/ten.wav"},
    {"10-107TAG", "Got a 10-107 here, send airwatch for tag", "npc/metropolice/vo/gota10-107sendairwatch.wav"},
    {"10-14DUTY", "Holding on 10-14 duty, code 4", "npc/metropolice/vo/holdingon10-14duty.wav"},
    {"10-2", "10-2", "npc/metropolice/vo/ten2.wav"},
    {"10-4", "10-4", "npc/metropolice/vo/10-4.wav"},
    {"10-4", "10-4", "npc/metropolice/vo/ten4.wav"},
    {"10-8STANDINGBY", "10-8 standing by", "npc/metropolice/vo/ten8standingby.wav"},
    {"10-97", "10-97", "npc/metropolice/vo/ten97.wav"},
    {"10-97GOA", "10-97 that suspect is GOA", "npc/metropolice/vo/ten97suspectisgoa.wav"},
    {"100", "One hundred", "npc/metropolice/vo/onehundred.wav"},
    {"11", "Eleven", "npc/metropolice/vo/eleven.wav"},
    {"11-44INBOUND", "Get that 11-44 inbound, we are cleaning up now", "npc/metropolice/vo/get11-44inboundcleaningup.wav"},
    {"11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav"},
    {"12", "12", "npc/metropolice/vo/twelve.wav"},
    {"13", "Thirteen", "npc/metropolice/vo/thirteen.wav"},
    {"14", "Fourteen", "npc/metropolice/vo/fourteen.wav"},
    {"15", "Fifteen", "npc/metropolice/vo/fifteen.wav"},
    {"16", "Sixteen", "npc/metropolice/vo/sixteen.wav"},
    {"17", "Seventeen", "npc/metropolice/vo/seventeen.wav"},
    {"18", "Eighteen", "npc/metropolice/vo/eighteen.wav"},
    {"19", "Nineteen", "npc/metropolice/vo/nineteen.wav"},
    {"2", "Two", "npc/metropolice/vo/two.wav"},
    {"20", "Twenty", "npc/metropolice/vo/twenty.wav"},
    {"200", "Two hundred", "npc/metropolice/vo/twohundred.wav"},
    {"3", "Three", "npc/metropolice/vo/three.wav"},
    {"30", "Thirty", "npc/metropolice/vo/thirty.wav"},
    {"300", "Three hundred", "npc/metropolice/vo/threehundred.wav"},
    {"4", "Four", "npc/metropolice/vo/four.wav"},
    {"40", "Fourty", "npc/metropolice/vo/fourty.wav"},
    {"404ZONE", "404 zone", "npc/metropolice/vo/404zone.wav"},
    {"408HERE", "I've got a 408 here at location", "npc/metropolice/vo/ivegot408hereatlocation.wav"},
    {"5", "Five", "npc/metropolice/vo/five.wav"},
    {"50", "Fifty", "npc/metropolice/vo/fifty.wav"},
    {"6", "Six", "npc/metropolice/vo/six.wav"},
    {"60", "Sixty", "npc/metropolice/vo/sixty.wav"},
    {"603", "603 unlawful entry", "npc/metropolice/vo/unlawfulentry603.wav"},
    {"63TRESSPASS", "63, criminal trespass", "npc/metropolice/vo/criminaltrespass63.wav"},
    {"7", "Seven", "npc/metropolice/vo/seven.wav"},
    {"70", "Seventy", "npc/metropolice/vo/seventy.wav"},
    {"8", "Eight", "npc/metropolice/vo/eight.wav"},
    {"80", "Eighty", "npc/metropolice/vo/eighty.wav"},
    {"9", "Nine", "npc/metropolice/vo/nine.wav"},
    {"90", "Ninety", "npc/metropolice/vo/ninety.wav"},
    {"ACQUIRINGVISUAL", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav"},
    {"AFFIRMATIVE", "Affirmative", "npc/metropolice/vo/affirmative.wav"},
    {"AFFIRMATIVE2", "Affirmative", "npc/metropolice/vo/affirmative2.wav"},
    {"AIRWATCH505", "Dispatch we need airwatch, subject is 505", "npc/metropolice/vo/airwatchsubjectis505.wav"},
    {"AIRWATCHBOL243", "CP, we need airwatch to BOL for that 243", "npc/metropolice/vo/cpbolforthat243.wav"},
    {"ALLUNITSATBOL", "All units at BOL, we have 34s at", "npc/metropolice/vo/allunitsbol34sat.wav"},
    {"ALLUNITSATLOCATIONCODE3", "All units at location, respond at code 3!", "npc/metropolice/vo/allunitsrespondcode3.wav"},
    {"ALLUNITSCODE2", "All units code 2", "npc/metropolice/vo/allunitscode2.wav"},
    {"ALLUNITSMAINTAINTHISCP", "All units maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav"},
    {"ALLUNITSMOVEIN", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav"},
    {"AMPUTATE", "Amputate", "npc/metropolice/vo/amputate.wav"},
    {"ANTICITIZEN", "Anti-Citizen", "npc/metropolice/vo/anticitizen.wav"},
    {"APPLY", "Apply", "npc/metropolice/vo/apply.wav"},
    {"ATCHECKPOINT", "At checkpoint", "npc/metropolice/vo/atcheckpoint.wav"},
    {"ATHARDPOINTREADYTOPROSECUTE", "is at hardpoint, ready to prosecute!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav"},
    {"BACKUP", "Backup", "npc/metropolice/vo/backup.wav"},
    {"BLOCK", "Block", "npc/metropolice/vo/block.wav"},
    {"BLOCKCOHESIVE", "Block is holding cohesive", "npc/metropolice/vo/blockisholdingcohesive.wav"},
    {"BREAKCOVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav"},
    {"CAN1", "Pick up that can", "npc/metropolice/vo/pickupthecan1.wav"},
    {"CAN2", "You knocked it over, pick it up", "npc/metropolice/vo/youknockeditover.wav"},
    {"CAN3", "Pick. Up. The. Can", "npc/metropolice/vo/pickupthecan2.wav"},
    {"CAN4", "I said pick up the can", "npc/metropolice/vo/pickupthecan3.wav"},
    {"CANAL", "Canal", "npc/metropolice/vo/canal.wav"},
    {"CANALBLOCK", "Canal Block", "npc/metropolice/vo/canalblock.wav"},
    {"CATCHBLIP", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav"},
    {"CAUTERIZE", "Cauterize", "npc/metropolice/vo/cauterize.wav"},
    {"CHECKFORMISCOUNT", "Check for miscount", "npc/metropolice/vo/checkformiscount.wav"},
    {"CHUCKLE", "*Chuckle*", "npc/metropolice/vo/chuckle.wav"},
    {"CITIZEN", "Citizen", "npc/metropolice/vo/citizen.wav"},
    {"CLEARCODE100", "Clear and Code 100", "npc/metropolice/vo/clearandcode100.wav"},
    {"CLEARNO647", "Clear no 647, no 10-107", "npc/metropolice/vo/clearno647no10-107.wav"},
    {"CLOSEONSUSPECT", "All units close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav"},
    {"CLOSINGONSUSPECT", "is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav"},
    {"CODE100", "Code 100", "npc/metropolice/vo/code100.wav"},
    {"CODE7", "Code 7", "npc/metropolice/vo/code7.wav"},
    {"CONDEMNEDZONE", "Condemned zone", "npc/metropolice/vo/condemnedzone.wav"},
    {"CONTACTWITH243", "Contact with 243 suspect, my 10-20 is", "npc/metropolice/vo/contactwith243suspect.wav"},
    {"CONTROL100", "Control is 100 percent at location, no sign of 647E", "npc/metropolice/vo/control100percent.wav"},
    {"CONTROLSECTION", "Control Section", "npc/metropolice/vo/controlsection.wav"},
    {"CONVERGING", "Converging", "npc/metropolice/vo/converging.wav"},
    {"COPY", "Copy", "npc/metropolice/vo/copy.wav"},
    {"COVERMEIN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav"},
    {"CPCOMPROMISED", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav"},
    {"CPESTABLISHPERIMETER", "CP, we need to establish a perimeter at", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav"},
    {"CPLOCATIONREPORT", "CP requests all units uh.. location report-in", "npc/metropolice/vo/cprequestsallunitsreportin.wav"},
    {"CPOVERRUN", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav"},
    {"CPREPORTSTATUS", "Local CPT, report status", "npc/metropolice/vo/localcptreportstatus.wav"},
    {"DBCOUNT", "DB count is", "npc/metropolice/vo/dbcountis.wav"},
    {"DBHERE", "Oh, we got a DB here cancel that 11-42", "npc/metropolice/vo/wegotadbherecancel10-102.wav"},
    {"DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav"},
    {"DESERVICEDAREA", "Deserviced area", "npc/metropolice/vo/deservicedarea.wav"},
    {"DESIGNATESUSPECTAS", "Designate suspect as", "npc/metropolice/vo/designatesuspectas.wav"},
    {"DESTROYTHATCOVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav"},
    {"DISMOUNTINGHARDPOINT", "Dismounting Hardpoint", "npc/metropolice/vo/dismountinghardpoint.wav"},
    {"DISPATCH10-78", "Dispatch, I need 10-78. Officer in trouble!", "npc/metropolice/vo/dispatchineed10-78.wav"},
    {"DISTRIBUTIONBLOCK", "Distribution Block", "npc/metropolice/vo/distributionblock.wav"},
    {"DOCUMENT", "Document", "npc/metropolice/vo/document.wav"},
    {"DONTMOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav"},
    {"EXAMINE", "Examine", "npc/metropolice/vo/examine.wav"},
    {"EXPIRED", "Expired", "npc/metropolice/vo/expired.wav"},
    {"EXTERNALJURISDICTION", "External Jurisdiction", "npc/metropolice/vo/externaljurisdiction.wav"},
    {"FINALVERDICT", "Final verdict administered", "npc/metropolice/vo/finalverdictadministered.wav"},
    {"FINALWARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav"},
    {"FIRINGEXPOSETARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav"},
    {"FIRSTWARNINGMOVE", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav"},
    {"GETDOWN", "Get down!", "npc/metropolice/vo/getdown.wav"},
    {"GETOUT", "Get out of here", "npc/metropolice/vo/getoutofhere.wav"},
    {"GOTHIMAGAIN", "Got him again, suspect is 10-20 at", "npc/metropolice/vo/gothimagainsuspect10-20at.wav"},
    {"GRENADE!", "Grenade!", "npc/metropolice/vo/grenade.wav"},
    {"HARDPOINTSCANNING", "Hardpoint scanning", "npc/metropolice/vo/hardpointscanning.wav"},
    {"HAVE10-108", "We have a 10-108!", "npc/metropolice/vo/wehavea10-108.wav"},
    {"HAVE10-30", "I have a 10-30 at my 10-20, respond code 2", "npc/metropolice/vo/ihave10-30my10-20responding.wav"},
    {"HELP!", "Help!", "npc/metropolice/vo/help.wav"},
    {"HELPWITHTHISONE", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav"},
    {"HERO", "Hero!", "npc/metropolice/vo/hero.wav"},
    {"HESGONE148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav"},
    {"HIGHREGION", "High priority region", "npc/metropolice/vo/highpriorityregion.wav"},
    {"HOLDIT", "Hold it!", "npc/metropolice/vo/holdit.wav"},
    {"HOLDPOSITION", "Protection team, hold this position!", "npc/metropolice/vo/holdthisposition.wav"},
    {"HOLDTHERE", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav"},
    {"INDUSTRIALZONE", "Industrial Zone", "npc/metropolice/vo/industrialzone.wav"},
    {"INFECTION", "Infection", "I have a 10-30 at my 10-20, respond code 2"},
    {"INFESTEDZONE", "Infested Zone", "npc/metropolice/vo/infestedzone.wav"},
    {"INJECT", "Inject!", "npc/metropolice/vo/inject.wav"},
    {"INNOCULATE", "Innoculate", "npc/metropolice/vo/innoculate.wav"},
    {"INPOSITION", "In position", "npc/metropolice/vo/inposition.wav"},
    {"INPOSITIONHARDPOINT", "In position at hardpoint", "npc/metropolice/vo/inpositionathardpoint.wav"},
    {"INTERCEDE", "Intercede", "npc/metropolice/vo/intercede.wav"},
    {"INTERLOCK", "Interlock", "npc/metropolice/vo/interlock.wav"},
    {"INVESTIGATE", "Investigate", "npc/metropolice/vo/investigate.wav"},
    {"INVESTIGATE10-103", "Investgating 10-103", "npc/metropolice/vo/investigating10-103.wav"},
    {"IS10-108", "is 10-108", "npc/metropolice/vo/is10-108.wav"},
    {"IS415B", "is 415B", "npc/metropolice/vo/is415b.wav"},
    {"ISDOWN", "is down!", "npc/metropolice/vo/isdown.wav"},
    {"ISMOVINGIN", "is moving in!", "npc/metropolice/vo/ismovingin.wav"},
    {"ISOLATE", "Isolate", "npc/metropolice/vo/isolate.wav"},
    {"ISPASSIVE", "is passive", "npc/metropolice/vo/ispassive.wav"},
    {"JURY", "Jury!", "npc/metropolice/vo/jury.wav"},
    {"KEEPMOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav"},
    {"KING", "King!", "npc/metropolice/vo/king.wav"},
    {"LEVEL3PRIVACY", "Found a level 3 civil privacy violator", "npc/metropolice/vo/level3civilprivacyviolator.wav"},
    {"LINE", "Line!", "npc/metropolice/vo/line.wav"},
    {"LOCATION", "Location", "npc/metropolice/vo/location.wav"},
    {"LOCK", "Lock", "npc/metropolice/vo/lock.wav"},
    {"LOCKPOSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav"},
    {"LOOKINGTROUBLE", "Looking for trouble?", "npc/metropolice/vo/lookingfortrouble.wav"},
    {"LOOKOUT", "Look out!", "npc/metropolice/vo/lookout.wav"},
    {"MALCOMPLIANCEVERDICT", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav"},
    {"MALCOPLIANT10-107", "Malcopliant 10-107 at my 10-20, ready to prosecute", "npc/metropolice/vo/malcompliant10107my1020.wav"},
    {"MALCOPLIANTCITATION", "Issuing malcopliant citation", "npc/metropolice/vo/issuingmalcompliantcitation.wav"},
    {"MALIGNANT", "Malignant", "npc/metropolice/vo/malignant.wav"},
    {"MOVE", "Move", "npc/metropolice/vo/move.wav"},
    {"MOVEALONG", "Move along", "npc/metropolice/vo/movealong.wav"},
    {"MOVEARRESTPOSITIONS", "All units, move to arrest positions", "npc/metropolice/vo/movetoarrestpositions.wav"},
    {"MOVEBACK", "Move back right now!", "npc/metropolice/vo/movebackrightnow.wav"},
    {"MOVEIT", "Move it", "npc/metropolice/vo/moveit2.wav"},
    {"MOVEIT2", "Move it!", "npc/metropolice/vo/moveit.wav"},
    {"MOVINGTOCOVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav"},
    {"NECROTICS", "Necrotics!", "npc/metropolice/vo/necrotics.wav"},
    {"NOCONTACT", "No contact", "npc/metropolice/vo/nocontact.wav"},
    {"NONCITIZEN", "Non-Citizen", "npc/metropolice/vo/noncitizen.wav"},
    {"NONPATROLREGION", "Non-Patrol Region", "npc/metropolice/vo/nonpatrolregion.wav"},
    {"NOVISUALONUPI", "No visual on UPI at this time", "npc/metropolice/vo/novisualonupi.wav"},
    {"NOWGETOUT", "Now, get out of here", "npc/metropolice/vo/nowgetoutofhere.wav"},
    {"OFFICERASSISTANCE", "Officer needs assitance, I'm 11-99!", "npc/metropolice/vo/officerneedsassistance.wav"},
    {"OFFICERDOWN", "Officer down, request all units code 3 to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav"},
    {"OFFICERDOWN10-99", "Officer down, I am 10-99, I repeat I am 10-99!", "npc/metropolice/vo/officerdowniam10-99.wav"},
    {"OFFICERFIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav"},
    {"OFFICERHELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav"},
    {"ONEACCOMPLICE", "I got one accomplice here", "npc/metropolice/vo/gotoneaccomplicehere.wav"},
    {"OUTBREAK", "Outbreak!", "npc/metropolice/vo/outbreak.wav"},
    {"OUTLANDZONE", "Outland Zone", "npc/metropolice/vo/outlandzone.wav"},
    {"PACIFY", "Pacify!", "npc/metropolice/vo/pacifying.wav"},
    {"PATROL", "Patrol!", "npc/metropolice/vo/patrol.wav"},
    {"PICKUP647E", "Anyone else pick up uh.. 647E reading?", "npc/metropolice/vo/anyonepickup647e.wav"},
    {"POSITIONCONTAIN", "Position to contain", "npc/metropolice/vo/positiontocontain.wav"},
    {"POSSIBLE404", "Possible 404 here", "npc/metropolice/vo/possible404here.wav"},
    {"POSSIBLELEVEL3VIOLATOR", "Possible level 3 civil privacy violator here", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav"},
    {"PREPARE10-15", "Prepare for 10-15", "npc/metropolice/vo/preparefor1015.wav"},
    {"PREPAREJUDGMENT", "Suspect, prepare to receive civil judgement", "npc/metropolice/vo/prepareforjudgement.wav"},
    {"PRESERVE", "Preserve", "npc/metropolice/vo/preserve.wav"},
    {"PRESSURE", "Pressure", "npc/metropolice/vo/pressure.wav"},
    {"PRODUCTIONBLOCK", "Production Block", "npc/metropolice/vo/productionblock.wav"},
    {"PROSECUTE", "Prosecute", "npc/metropolice/vo/prosecute.wav"},
    {"PROTECTIONCOMPLETE", "Protection complete", "npc/metropolice/vo/protectioncomplete.wav"},
    {"PTATLOCATIONREPORT", "Protection teams at location, report in", "npc/metropolice/vo/ptatlocationreport.wav"},
    {"QUICK", "Quick!", "npc/metropolice/vo/quick.wav"},
    {"READYAMPUTATE", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav"},
    {"READYJUDGE", "Ready to judge!", "npc/metropolice/vo/readytojudge.wav"},
    {"READYPROSECUTE", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav"},
    {"READYPROSECUTEWARNING", "Ready to prosecute malcopliant citizen, final warning issued"},
    {"REINFORCEMENTCODE3", "Reinforcement teams, code 3!", "npc/metropolice/vo/reinforcementteamscode3.wav"},
    {"REPORTLOCATIONSUSPECT", "All units report locations of suspect", "npc/metropolice/vo/allunitsreportlocationsuspect.wav"},
    {"REPORTSIGHTACCOMPLICES", "Report sights of possible accomplices", "npc/metropolice/vo/reportsightingsaccomplices.wav"},
    {"RESIDENTALBLOCK", "Residental Block", "npc/metropolice/vo/residentialblock.wav"},
    {"RESPONDING", "Responding!", "npc/metropolice/vo/responding2.wav"},
    {"RESTRICT", "Restrict", "npc/metropolice/vo/restrict.wav"},
    {"RESTRICTEDBLOCK", "Restricted Block", "npc/metropolice/vo/restrictedblock.wav"},
    {"RODGERTHAT", "Rodger that", "npc/metropolice/vo/rodgerthat.wav"},
    {"ROLLER", "Roller!", "npc/metropolice/vo/roller.wav"},
    {"RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav"},
    {"SACRIFICECODEMAINTAIN", "All units sacrifice code 1 and maintain this CP!", "npc/metropolice/vo/sacrificecode1maintaincp.wav"},
    {"SAIDMOVEALONG", "I said move along!", "npc/metropolice/vo/isaidmovealong.wav"},
    {"SEARCH", "Search!", "npc/metropolice/vo/search.wav"},
    {"SEARCHINGFORSUSPECT", "Searching for suspect, no status", "npc/metropolice/vo/searchingforsuspect.wav"},
    {"SECONDWARNING", "Second warning given!", "npc/metropolice/vo/secondwarning.wav"},
    {"SECTOR", "Sector", "npc/metropolice/vo/sector.wav"},
    {"SENTENCEDELIVERED", "Sentence delivered", "npc/metropolice/vo/sentencedelivered.wav"},
    {"SERVE", "Serve", "npc/metropolice/vo/serve.wav"},
    {"SHIT", "Shit!", "npc/metropolice/vo/shit.wav"},
    {"SHOTSFIRED", "Shots fired, hostile malignants here", "npc/metropolice/vo/shotsfiredhostilemalignants.wav"},
    {"SOCIOCIDE", "Sociocide", "npc/metropolice/vo/sociocide.wav"},
    {"SOCIOSTABLE", "We are socio-stable at this location", "npc/metropolice/vo/wearesociostablethislocation.wav"},
    {"STABILIZATIONJURISDICTION", "Stabilization Jurisdiction", "npc/metropolice/vo/stabilizationjurisdiction.wav"},
    {"STATIONBLOCK", "Station Block", "npc/metropolice/vo/stationblock.wav"},
    {"STERILIZE", "Sterilize", "npc/metropolice/vo/sterilize.wav"},
    {"STICK", "Stick", "npc/metropolice/vo/stick.wav"},
    {"STORMSYSTEM", "Storm System", "npc/metropolice/vo/stormsystem.wav"},
    {"SUBJECT", "Subject", "npc/metropolice/vo/subject.wav"},
    {"SUBJECT505", "Subject is 505", "npc/metropolice/vo/subjectis505.wav"},
    {"SUSPECTLOCATIONUNKNOWN", "Suspect location unknown", "npc/metropolice/vo/suspectlocationunknown.wav"},
    {"SUSPEND", "Suspend!", "npc/metropolice/vo/suspend.wav"},
    {"SWEEPINGSUSPECT", "Sweeping for suspect", "npc/metropolice/vo/sweepingforsuspect.wav"},
    {"TAGNECROTIC", "Tag one necrotic!", "npc/metropolice/vo/tagonenecrotic.wav"},
    {"TAGPARASITE", "Tag one parasite!", "npc/metropolice/vo/tagoneparasitic.wav"},
    {"TAKEALOOK", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav"},
    {"TAKECOVER", "Take cover!", "npc/metropolice/vo/takecover.wav"},
    {"TAP", "Tap!", "npc/metropolice/vo/tap.wav"},
    {"TEAMPOSITIONADVANCE", "Team in position, advance", "npc/metropolice/vo/teaminpositionadvance.wav"},
    {"THAT'SAGRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav"},
    {"THATSAGRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav"},
    {"THEREHEIS", "There he is!", "npc/metropolice/vo/thereheis.wav"},
    {"THISSECONDWARNING", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav"},
    {"TRANSIT BLOCK", "Transit Block", "npc/metropolice/vo/transitblock.wav"},
    {"TRASH1", "Now put it in the trash can", "npc/metropolice/vo/putitinthetrash1.wav"},
    {"TRASH2", "I said put it in the trash can", "npc/metropolice/vo/putitinthetrash2.wav"},
    {"UNION", "Union!", "npc/metropolice/vo/union.wav"},
    {"UNIT10-65", "Unit is 10-65", "npc/metropolice/vo/unitis10-65.wav"},
    {"UNIT10-8STANDINGBY", "Unit is 10-8 standing by", "npc/metropolice/vo/unitis10-8standingby.wav"},
    {"UNITISONDUTY", "Unit is on duty, 10-8", "npc/metropolice/vo/unitisonduty10-8.wav"},
    {"UPI", "UPI", "npc/metropolice/vo/upi.wav"},
    {"UPTHERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav"},
    {"VACATECITIZEN", "Vacate citizen", "npc/metropolice/vo/vacatecitizen.wav"},
    {"VICE", "Vice!", "npc/metropolice/vo/vice.wav"},
    {"VICTOR", "Victor!", "npc/metropolice/vo/victor.wav"},
    {"VISCERATORDEPLOYED", "Viscerator deployed!", "npc/metropolice/vo/visceratordeployed.wav"},
    {"WASTERIVER", "Wasteriver", "npc/metropolice/vo/wasteriver.wav"},
    {"WATCHIT", "Watch it!", "npc/metropolice/vo/watchit.wav"},
    {"WORKFORCEINTAKE", "Workforce Intake", "npc/metropolice/vo/workforceintake.wav"},
    {"XRAY", "XRay", "npc/metropolice/vo/xray.wav"},
    {"YELLOW", "Yellow!", "npc/metropolice/vo/yellow.wav"},
    {"YOU CAN GO", "Alright, you can go", "npc/metropolice/vo/allrightyoucango.wav"},
    {"ZONE", "Zone", "npc/metropolice/vo/zone.wav"},

    {"TAKEHIMDOWN", "Take him down!", "npc/metropolice/takedown.wav"},

    {"AFFIRMATIVEGOTHIM", "Affirmative, we got him now", "npc/combine_soldier/vo/affirmativewegothimnow.wav"},
    {"CONTACT", "Contact", "npc/combine_soldier/vo/contact.wav"},
    {"CONTACTCONFIRMED", "Contact confirmed", "npc/combine_soldier/vo/contactconfim.wav"},
    {"CONTACTCONFIRMEDPROSECUTING", "Contact confirmed prosecuting", "npc/combine_soldier/vo/contactconfirmprosecuting.wav"},
    {"ENGAGING", "Engaging", "npc/combine_soldier/vo/engaging.wav"},
    {"FLATLINE", "Flatline", "npc/combine_soldier/vo/flatline.wav"},
    {"GOSHARP", "Go sharp", "npc/combine_soldier/vo/gosharp.wav"},
    {"GOSHARP2", "Go sharp, go sharp", "npc/combine_soldier/vo/gosharpgosharp.wav"},
    {"MOVEIN", "Move in", "npc/combine_soldier/vo/movein.wav"},
    {"PREPFORCONTACT", "Prep for contact, report in", "npc/combine_soldier/vo/prepforcontact.wav"},
    {"PROSECUTING", "Prosecuting", "npc/combine_soldier/vo/prosecuting.wav"},
    {"READYWEAPONS", "Ready weapons", "npc/combine_soldier/vo/readyweapons.wav"},
    {"READYWEAPONSHOSTILES", "Ready weapons, possible hostiles inbound", "npc/combine_soldier/vo/readyweaponshostilesinbound.wav"},
    {"REPORTINGCLEAR", "Reporting clear", "npc/combine_soldier/vo/reportingclear.wav"},
    {"REPORTPOSITIONSCLEAR", "Report all positions clear", "npc/combine_soldier/vo/reportallpositionsclear.wav"},
    {"REPORTRADIALSFREE", "Report all radials free", "npc/combine_soldier/vo/reportallradialsfree.wav"},
    {"REQUESTMEDICAL", "Request medical", "npc/combine_soldier/vo/requestmedical.wav"},
    {"RIPCORD", "Ripcord", "npc/combine_soldier/vo/ripcord.wav"},
    {"RIPCORD2", "Ripcord, ripcord", "npc/combine_soldier/vo/ripcordripcord.wav"},
    {"SECTOR", "Sector", "npc/combine_soldier/vo/sector.wav"},
    {"SECTORNOTSECURE", "Sector is not secure", "npc/combine_soldier/vo/sectorisnotsecure.wav"},
    {"SECTORSECURE", "Sector is secure, no viscon", "npc/combine_soldier/vo/sectorissecurenovison.wav"},
    {"SECURE", "Secure", "npc/combine_soldier/vo/secure.wav"}
}

for k, v in ipairs(cpVoicelines) do
    Schema.voices.Add("CivilProtection", v[1], v[2], v[3])
end

Schema.voices.AddClass("CivilProtection", function(ply)
    return Schema:IsCP(ply)
end)