// Schema.voices.Add("Class", "Text", "Real Text.", "sound")

local function AddVoice(text, realtext, sound)
    Schema.voices.Add("CivilProtection", text, realtext, sound)
end

AddVoice("11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
AddVoice("404ZONE", "404 zone.", "npc/metropolice/vo/404zone.wav")
AddVoice("ACQUIRINGVISUAL", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
AddVoice("AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
AddVoice("AFFIRMATIVE2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav")
AddVoice("10-4", "10-4.", "npc/metropolice/vo/10-4.wav")
AddVoice("AIRWATCH505", "Dispatch we need airwatch, subject is 505.", "npc/metropolice/vo/airwatchsubjectis505.wav")
AddVoice("YOU CAN GO", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
AddVoice("ALLUNITSATBOL", "All units at BOL, we have 34s at", "npc/metropolice/vo/allunitsbol34sat.wav")
AddVoice("CLOSEONSUSPECT", "All units close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
AddVoice("ALLUNITSCODE2", "All units code 2.", "npc/metropolice/vo/allunitscode2.wav") // same as above
AddVoice("ALLUNITSMAINTAINTHISCP", "All units maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
AddVoice("ALLUNITSMOVEIN", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav")
AddVoice("REPORTLOCATIONSUSPECT", "All units report locations of suspect.", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
AddVoice("ALLUNITSATLOCATIONCODE3", "All units at location, respond at code 3!", "npc/metropolice/vo/allunitsrespondcode3.wav")
AddVoice("AMPUTATE", "Amputate.", "npc/metropolice/vo/amputate.wav")
AddVoice("ANTICITIZEN", "Anti-Citizen.", "npc/metropolice/vo/anticitizen.wav")
AddVoice("PICKUP647E", "Anyone else pick up uh.. 647E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
AddVoice("APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
AddVoice("ATCHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
AddVoice("BACKUP", "Backup.", "npc/metropolice/vo/backup.wav")
AddVoice("BLOCK", "Block.", "npc/metropolice/vo/block.wav")
AddVoice("BLOCKCOHESIVE", "Block is holding cohesive", "npc/metropolice/vo/blockisholdingcohesive.wav")
AddVoice("BREAKCOVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
AddVoice("CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
AddVoice("CANALBLOCK", "Canal Block.", "npc/metropolice/vo/canalblock.wav")
AddVoice("CATCHBLIP", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav")
AddVoice("CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
AddVoice("CHECKFORMISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
AddVoice("CHUCKLE", "*Chuckle*", "npc/metropolice/vo/chuckle.wav")
AddVoice("CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
AddVoice("CLEARCODE100", "Clear and Code 100.", "npc/metropolice/vo/clearandcode100.wav")
AddVoice("CLEARNO647", "Clear no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
AddVoice("CODE100", "Code 100.", "npc/metropolice/vo/code100.wav")
AddVoice("CODE7", "Code 7.", "npc/metropolice/vo/code7.wav")
AddVoice("CONDEMNEDZONE", "Condemned zone.", "npc/metropolice/vo/condemnedzone.wav")
AddVoice("CONTACTWITH243", "Contact with 243 suspect, my 10-20 is", "npc/metropolice/vo/contactwith243suspect.wav")
AddVoice("CONTROL100", "Control is 100 percent at location, no sign of 647E.", "npc/metropolice/vo/control100percent.wav")
AddVoice("CONTROLSECTION", "Control Section.", "npc/metropolice/vo/controlsection.wav")
AddVoice("CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
AddVoice("COPY", "Copy.", "npc/metropolice/vo/copy.wav")
AddVoice("COVERMEIN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
AddVoice("AIRWATCHBOL243", "CP, we need airwatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
AddVoice("CPCOMPROMISED", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
AddVoice("CPOVERRUN", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
AddVoice("CPLOCATIONREPORT", "CP requests all units uh.. location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
AddVoice("CPESTABLISHPERIMETER", "CP, we need to establish a perimeter at.", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
AddVoice("63TRESSPASS", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
AddVoice("DBCOUNT", "DB count is.", "npc/metropolice/vo/dbcountis.wav")
AddVoice("DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav")
AddVoice("DESERVICEDAREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
AddVoice("DESIGNATESUSPECTAS", "Designate suspect as.", "npc/metropolice/vo/designatesuspectas.wav")
AddVoice("DESTROYTHATCOVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
AddVoice("DISMOUNTINGHARDPOINT", "Dismounting Hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
AddVoice("DISPATCH10-78", "Dispatch, I need 10-78. Officer in trouble!", "npc/metropolice/vo/dispatchineed10-78.wav")
AddVoice("DISTRIBUTIONBLOCK", "Distribution Block.", "npc/metropolice/vo/distributionblock.wav")
AddVoice("DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
AddVoice("DONTMOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
AddVoice("8", "Eight", "npc/metropolice/vo/eight.wav")
AddVoice("18", "Eighteen", "npc/metropolice/vo/eighteen.wav")
AddVoice("80", "Eighty", "npc/metropolice/vo/eighty.wav")
AddVoice("11", "Eleven", "npc/metropolice/vo/eleven.wav")
AddVoice("EXAMINE", "Examine.", "npc/metropolice/vo/examine.wav")
AddVoice("EXPIRED", "Expired.", "npc/metropolice/vo/expired.wav")
AddVoice("EXTERNALJURISDICTION", "External Jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
AddVoice("15", "Fifteen", "npc/metropolice/vo/fifteen.wav")
AddVoice("50", "Fifty", "npc/metropolice/vo/fifty.wav")
AddVoice("FINALVERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
AddVoice("FINALWARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
AddVoice("FIRINGEXPOSETARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
AddVoice("FIRSTWARNINGMOVE", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
AddVoice("5", "Five.", "npc/metropolice/vo/five.wav")
AddVoice("4", "Four.", "npc/metropolice/vo/four.wav")
AddVoice("14", "Fourteen.", "npc/metropolice/vo/fourteen.wav")
AddVoice("40", "Fourty", "npc/metropolice/vo/fourty.wav")

Schema.voices.AddClass("CivilProtection", function(ply)
	return Schema:IsCP(ply)
end)