local citizenMaleVCs = {
    {"BE CAREFUL", "Be careful now.", "vo/canals/boxcar_becareful.wav"},
    {"CAN'T AFFORD", "We really can't afford to get noticed.", "vo/canals/boxcar_becareful_b.wav"},
    {"GET GOING", "Get going now.", "vo/canals/boxcar_go_nag01.wav"},
    {"GET GOING2", "Better get going.", "vo/canals/boxcar_go_nag02.wav"},
    {"GET OUTTA HERE", "Get outta here.", "vo/canals/boxcar_go_nag03.wav"},
    {"HIT THE ROAD JACK", "Hit the road, Jack.", "vo/canals/boxcar_go_nag04.wav"},
    {"HELL HELP YOU", "He'll help you if you let him.", "vo/canals/boxcar_lethimhelp.wav"},
    {"SIREN SARE FOR YOU", "Guess those sirens are for you, huh?", "vo/canals/boxcar_sirens.wav"},
    {"YOU FOUND US", "Good thing you found us.", "vo/canals/boxcar_sirens_b.wav"},
    {"ILL SHOW YOU", "Come on in, I'll show you what you're up against.", "vo/canals/gunboat_comein.wav"},
    {"FINISHING UP NOW", "I think he's just finishing up now.", "vo/canals/gunboat_finishingup.wav"},
    {"GET IN HERE", "Come on, get in here.", "vo/canals/gunboat_getin.wav"},
    {"GO ON OUT", "Go on out.", "vo/canals/gunboat_goonout.wav"},
    {"TAKE A LOOK AT THIS", "Here, take a look at this.", "vo/canals/gunboat_herelook.wav"},
    {"POOR BASTARD", "Poor bastard doesn't stand a chance.", "vo/canals/matt_beglad_b.wav"},
    {"CLOSE CALL", "That was a close call. Thanks for your help.", "vo/canals/matt_closecall.wav"},
    {"BEFORE THEY SWEEP", "You better get going before they sweep through here.", "vo/canals/matt_flood_b.wav"},
    {"GET IN HERE2", "Get in here, hurry!", "vo/canals/matt_getin.wav"},
    {"GET GOING NOW", "You better get going now.", "vo/canals/matt_go_nag01.wav"},
    {"GET GOING3", "Get going.", "vo/canals/matt_go_nag04.wav"},
    {"GO ON2", "You go on.", "vo/canals/matt_go_nag05.wav"},
    {"GOOD LUCK OUT THERE", "Good luck out there!", "vo/canals/matt_goodluck.wav"},
    {"TOO LATE", "Oh shit! Too late!", "vo/canals/matt_toolate.wav"},
    {"BAD TIME", "You got here at a bad time.", "vo/canals/shanty_badtime.wav"},
    {"GET OUTTA HERE2", "Get outta here!", "vo/canals/shanty_go_nag01.wav"},
    {"GO ON", "Go on!", "vo/canals/shanty_go_nag02.wav"},
    {"GET GOING4", "Get going!", "vo/canals/shanty_go_nag03.wav"},
    {"HEY", "Hey!", "vo/canals/shanty_hey.wav"},
    {"INCOMING", "Incoming!", "vo/canals/male01/stn6_incoming.wav"},
    {"THEYRE SHELLING US", "They're shelling us!", "vo/canals/male01/stn6_shellingus.wav"},
    {"BAD NEWS", "Civil Protection catches you down here, it's bad news for the whole railroad.", "vo/canals/boxcar_becareful_c.wav"},
    {"HERE COME THE DROPSHIPS", "Oh crap! Here come the dropships!", "vo/coast/barn/male01/crapships.wav"},
    {"OFF THE ROAD", "Get off the road!", "vo/coast/barn/male01/getoffroad01.wav"},
    {"INCOMING DROPSHIP", "Incoming dropship!", "vo/coast/barn/male01/incomingdropship.wav"},
    {"GUNSHIP", "It's a gunship!", "vo/coast/barn/male01/lite_gunship01.wav"},
    {"GUNSHIP2", "Gunship!", "vo/coast/barn/male01/lite_gunship02.wav"},
    {"YOU MADE IT", "You made it!", "vo/coast/barn/male01/youmadeit.wav"},
    {"NO HELP", "No, help!", "vo/coast/bugbait/sandy_help.wav"},
    {"YOU THERE", "You there!", "vo/coast/bugbait/sandy_youthere.wav"},
    {"FOLLOW ME", "Follow me.", "vo/coast/cardock/le_followme.wav"},
    {"GOOD IDEA", "Yeah good idea. Hold on a sec.", "vo/coast/cardock/le_goodidea.wav"},
    {"PATCH HIM UP", "Patch him up and get him to the back as soon as he's stable.", "vo/coast/cardock/le_patchhim.wav"},
    {"WHOSHURT", "Who's hurt?", "vo/coast/cardock/le_whohurt.wav"},
    {"CHEER", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer01.wav"},
    {"CHEER2", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer02.wav"},
    {"CHEER3", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer03.wav"},
    {"CHEER4", "*Cheering.*", "vo/coast/odessa/male01/nlo_cheer03.wav"},
    {"DRIVE SAFELY", "Drive safely.", "vo/coast/odessa/male01/nlo_citizen_drivesafe.wav"},
    {"NOO", "No, Nooo!", "vo/coast/odessa/male01/nlo_cubdeath01.wav"},
    {"NOO2", "No! Noooo!", "vo/coast/odessa/male01/nlo_cubdeath02.wav"},
    {"THIS WAY", "This way.", "vo/coast/odessa/male01/stairman_follow01.wav"},
    {"GOOD TO KNOW YOU", "Good to know you.", "vo/eli_lab/airlock_cit01.wav"},
    {"BETTER GET GOING", "You better get going.", "vo/eli_lab/airlock_cit02.wav"},
    {"AMMO", "Here, ammo!", "vo/npc/male01/ammo03.wav"},
    {"AMMO2", "Take some ammo!", "vo/npc/male01/ammo04.wav"},
    {"AMMO3", "Take some ammo!", "vo/npc/male01/ammo05.wav"},
    {"YOU ALL OVER", "That's you all over.", "vo/npc/male01/answer01.wav"},
    {"WONT HOLD IT AGAINST YOU", "I wont hold it against you.", "vo/npc/male01/answer02.wav"},
    {"FIGURES", "Figures.", "vo/npc/male01/answer03.wav"},
    {"TRY NOT TO DWELL", "Try not to dwell on it.", "vo/npc/male01/answer04.wav"},
    {"CAN WE TALK LATER", "Can we talk about this later?", "vo/npc/male01/answer05.wav"},
    {"SAME HERE", "Same here.", "vo/npc/male01/answer07.wav"},
    {"KNOW WHAT YOU MEAN", "Know what you mean.", "vo/npc/male01/answer08.wav"},
    {"TALKING TO YOURSELF", "You're taking to yourself again.", "vo/npc/male01/answer09.wav"},
    {"WOULDNT SAY TOO LOUD", "I wouldn't say that too loud.", "vo/npc/male01/answer10.wav"},
    {"TOMB STONE", "I'll put it on your tombstone.", "vo/npc/male01/answer11.wav"},
    {"BEAR THINKING ABOUT", "Doesn't bear thinking about.", "vo/npc/male01/answer12.wav"},
    {"IM WITH YOU", "I'm with you.", "vo/npc/male01/answer13.wav"},
    {"YOU AND ME BOTH", "You and me both.", "vo/npc/male01/answer14.wav"},
    {"ONE WAY", "That's... one way of looking at it.", "vo/npc/male01/answer15.wav"},
    {"ORIGINAL THOUGHT", "Have you ever had an original thought?", "vo/npc/male01/answer16.wav"},
    {"SHUT UP", "I'm not even gonna tell you to shut up.", "vo/npc/male01/answer17.wav"},
    {"CONCENTRATE", "Let's concentrate on the task at hand.", "vo/npc/male01/answer18.wav"},
    {"MIND ON YOUR WORK", "Keep your mind on your work.", "vo/npc/male01/answer19.wav"},
    {"IN THE GUTTER", "Your mind is in the gutter.", "vo/npc/male01/answer20.wav"},
    {"DON'T BE SO SURE", "Don't be so sure of that.", "vo/npc/male01/answer21.wav"},
    {"YOU NEVER KNOW", "You never know.", "vo/npc/male01/answer22.wav"},
    {"NEVER CAN'T TELL", "Never can't tell.", "vo/npc/male01/answer23.wav"},
    {"TELLING ME", "Why are you telling me?", "vo/npc/male01/answer24.wav"},
    {"HOW ABOUT THAT", "How about that.", "vo/npc/male01/answer25.wav"},
    {"MORE INFORMATION", "That's more information than I require.", "vo/npc/male01/answer26.wav"},
    {"WANNA BET", "Wanna bet?", "vo/npc/male01/answer27.wav"},
    {"WISH I HAD A DIME", "I wish I had a dime for every time somebody said that.", "vo/npc/male01/answer28.wav"},
    {"WHAT AM I SUPPOSED TO DO", "What am I supposed to do about it?", "vo/npc/male01/answer29.wav"},
    {"TALKING TO ME", "You talking to me?", "vo/npc/male01/answer30.wav"},
    {"NIP THAT TALK", "You should nip that kind of talk in the bud.", "vo/npc/male01/answer31.wav"},
    {"RIGHT ON", "Right on.", "vo/npc/male01/answer32.wav"},
    {"NO ARGUMENT", "No argument there.", "vo/npc/male01/answer33.wav"},
    {"DON'T FORGET HAWAII", "Don't forget Hawaii", "vo/npc/male01/answer34.wav"},
    {"DON'T LET IT GET TO YOU", "Try not to let it get to you.", "vo/npc/male01/answer35.wav"},
    {"WOULDN'T BE THE FIRST TIME", "Wouldn't be the first time.", "vo/npc/male01/answer36.wav"},
    {"SURE ABOUT THAT", "You sure about that?", "vo/npc/male01/answer37.wav"},
    {"LEAVE IT", "Leave it alone.", "vo/npc/male01/answer38.wav"},
    {"ENOIGH OUTTA YOU", "That's enough outta you.", "vo/npc/male01/answer39.wav"},
    {"FIRST TIME FOR EVERYTHING", "There's a first time for everything.", "vo/npc/male01/answer40.wav"},
    {"BEHIND YOU", "Behind you!", "vo/npc/male01/behindyou01.wav"},
    {"BEHIND YOU2", "Behind you!", "vo/npc/male01/behindyou02.wav"},
    {"IM BUSY", "Can't you see I'm busy?", "vo/npc/male01/busy02.wav"},
    {"SUPPLIES", "Hey down there! Supplies!", "vo/npc/male01/cit_dropper01.wav"},
    {"LOOK OUT BELOW", "Look out below!", "vo/npc/male01/cit_dropper04.wav"},
    {"CIVIL PROTECTION", "Civil Protection!", "vo/npc/male01/civilprotection01.wav"},
    {"CIVILP ROTECTION2", "Civil Protection!", "vo/npc/male01/civilprotection02.wav"},
    {"COMBINE", "Combine!", "vo/npc/male01/combine01.wav"},
    {"COMBINE2", "Combine!", "vo/npc/male01/combine02.wav"},
    {"RELOADING", "Cover me while I reload!", "vo/npc/male01/coverwhilereload01.wav"},
    {"RELOADING2", "Cover me while I reload!", "vo/npc/male01/coverwhilereload02.wav"},
    {"CPS", "CPs!", "vo/npc/male01/cps01.wav"},
    {"CPS2", "CPs!", "vo/npc/male01/cps02.wav"},
    {"DOING SOMETHING", "Shouldn't we be doing something?", "vo/npc/male01/doingsomething.wav"},
    {"EVEN THE ODDS", "Let's even the odds a little.", "vo/npc/male01/evenodds.wav"},
    {"EXCUSE ME", "Excuse me.", "vo/npc/male01/excuseme01.wav"},
    {"EXCUSE ME2", "Excuse me.", "vo/npc/male01/excuseme02.wav"},
    {"FANTASTIC", "Fantastic.", "vo/npc/male01/fantastic01.wav"},
    {"FANTASTIC2", "Fantastic.", "vo/npc/male01/fantastic02.wav"},
    {"FINALLY", "Finally.", "vo/npc/male01/finally.wav"},
    {"GET DOWN", "Get down!", "vo/npc/male01/getdown02.wav"},
    {"GET GOING SOON", "Are we gonna get going soon?", "vo/npc/male01/getgoingsoon.wav"},
    {"GET THE HELL OUTTA HERE", "Get the hell outta here!", "vo/npc/male01/gethellout.wav"},
    {"GOOD GOD", "Good god!", "vo/npc/male01/goodgod.wav"},
    {"NOW WHAT", "Now what?", "vo/npc/male01/gordead_ans01.wav"},
    {"GOING SOWELL", "And things were going so well.", "vo/npc/male01/gordead_ans02.wav"},
    {"DON'T TELL ME", "Don't tell me.", "vo/npc/male01/gordead_ans03.wav"},
    {"OH GOD", "Oh God.", "vo/npc/male01/gordead_ans04.wav"},
    {"OH NO", "Oh no.", "vo/npc/male01/gordead_ans05.wav"},
    {"PLEASE NO", "Please, no.", "vo/npc/male01/gordead_ans06.wav"},
    {"IF YOU DARE SAY", "If you dare say 'That's gotta hurt', I'll kill you.", "vo/npc/male01/gordead_ans07.wav"},
    {"SHOULD WE BURY HIM", "Should we bury him here?", "vo/npc/male01/gordead_ans08.wav"},
    {"SPREAD THE WORD", "Spread the word.", "vo/npc/male01/gordead_ans10.wav"},
    {"WHATS THE USE", "What's the use?", "vo/npc/male01/gordead_ans11.wav"},
    {"WHATS THE POINT", "What's the point?", "vo/npc/male01/gordead_ans12.wav"},
    {"WHY GO ON", "Why go on?", "vo/npc/male01/gordead_ans13.wav"},
    {"WERE DONE FOR", "We're done for.", "vo/npc/male01/gordead_ans14.wav"},
    {"NOW WHAT2", "Well, now what?", "vo/npc/male01/gordead_ans15.wav"},
    {"DONE THIS BEFORE", "He's done this before, he'll be ok.", "vo/npc/male01/gordead_ans18.wav"},
    {"IM GONNA BE SICK", "I'm gonna be sick.", "vo/npc/male01/gordead_ans19.wav"},
    {"HES DEAD", "He's dead.", "vo/npc/male01/gordead_ques01.wav"},
    {"WAY TO GO", "What a way to go.", "vo/npc/male01/gordead_ques02.wav"},
    {"THIS CAN'T BE", "This can't be.", "vo/npc/male01/gordead_ques06.wav"},
    {"HES DEAD2", "Look, he's dead!", "vo/npc/male01/gordead_ques07.wav"},
    {"THIS IS BAD", "This is bad.", "vo/npc/male01/gordead_ques10.wav"},
    {"NOT SUPPOSED TO END", "It's not supposed to end like this!", "vo/npc/male01/gordead_ques14.wav"},
    {"WHAT NOW", "What now?", "vo/npc/male01/gordead_ques16.wav"},
    {"GOT ONE", "Got one!", "vo/npc/male01/gotone01.wav"},
    {"GOT ONE2", "I got one!", "vo/npc/male01/gotone02.wav"},
    {"RELOADING3", "Gotta reload.", "vo/npc/male01/gottareload01.wav"},
    {"GUNSHIP3", "Gunship!", "vo/npc/male01/gunship02.wav"},
    {"HEADCRABS", "Headcrabs!", "vo/npc/male01/headcrabs01.wav"},
    {"HEADCRABS2", "Headcrabs!", "vo/npc/male01/headcrabs02.wav"},
    {"HEADS UP", "Heads up!", "vo/npc/male01/headsup01.wav"},
    {"HEADS UP2", "Heads up!", "vo/npc/male01/headsup02.wav"},
    {"MEDKIT", "Take this medkit.", "vo/npc/male01/health01.wav"},
    {"MEDKIT2", "Take this medkit.", "vo/npc/male01/health02.wav"},
    {"MEDKIT3", "Take this medkit.", "vo/npc/male01/health03.wav"},
    {"MEDKIT4", "Here, have a medkit.", "vo/npc/male01/health04.wav"},
    {"MEDKIT5", "Here, patch yourself up.", "vo/npc/male01/health05.wav"},
    {"HELP", "Help!", "vo/npc/male01/help01.wav"},
    {"HERE COME THE HACKS", "Here come the hacks!", "vo/npc/male01/herecomehacks01.wav"},
    {"HERE COME THE HACKS2", "Here come the hacks!", "vo/npc/male01/herecomehacks02.wav"},
    {"HERE THEY COME", "Here they come!", "vo/npc/male01/heretheycome01.wav"},
    {"HI", "Hi.", "vo/npc/male01/hi01.wav"},
    {"HI2", "Hi.", "vo/npc/male01/hi02.wav"},
    {"HIT IN THE GUT", "Hit in the gut.", "vo/npc/male01/hitingut01.wav"},
    {"HIT IN THE GUT2", "Hit in the gut.", "vo/npc/male01/hitingut02.wav"},
    {"HOLD DOWN THIS SPOT", "I'm gonna stay and hold down this spot.", "vo/npc/male01/holddownspot01.wav"},
    {"HOLD DOWN THIS SPOT2", "I'm gonna stay and hold down this spot.", "vo/npc/male01/holddownspot02.wav"},
    {"ILL STAY HERE", "I'll stay here.", "vo/npc/male01/illstayhere01.wav"},
    {"IM HURT", "I'm hurt.", "vo/npc/male01/imhurt01.wav"},
    {"IM HURT2", "I'm hurt.", "vo/npc/male01/imhurt02.wav"},
    {"IM STICKING HERE", "I'm sticking here.", "vo/npc/male01/imstickinghere01.wav"},
    {"IN COMING2", "Incoming!", "vo/npc/male01/incoming02.wav"},
    {"ITS A MANHACK", "It's a manhack!", "vo/npc/male01/itsamanhack01.wav"},
    {"ITS A MANKACK2", "It's a manhack!", "vo/npc/male01/itsamanhack02.wav"},
    {"LEAD THE WAY", "You lead the way!", "vo/npc/male01/leadtheway01.wav"},
    {"LEAD THE WAY2", "Lead the way!", "vo/npc/male01/leadtheway02.wav"},
    {"LETS GO", "Let's go!", "vo/npc/male01/letsgo01.wav"},
    {"LETS GO2", "Let's go!", "vo/npc/male01/letsgo02.wav"},
    {"LIKE THAT", "Like that?!", "vo/npc/male01/likethat.wav"},
    {"CORNER", "I've got my little corner and I'm sticking to it.", "vo/npc/male01/littlecorner01.wav"},
    {"GROAN", "*Groan*", "vo/npc/male01/moan01.wav"},
    {"GROAN2", "*Groan*", "vo/npc/male01/moan02.wav"},
    {"GROAN3", "*Groan*", "vo/npc/male01/moan03.wav"},
    {"GROAN4", "*Groan*", "vo/npc/male01/moan04.wav"},
    {"GROAN5", "*Groan*", "vo/npc/male01/moan05.wav"},
    {"MY ARM", "My arm.", "vo/npc/male01/myarm01.wav"},
    {"MY ARM2", "My arm.", "vo/npc/male01/myarm02.wav"},
    {"MY GUT", "My gut.", "vo/npc/male01/mygut02.wav"},
    {"MY LEG", "My leg.", "vo/npc/male01/myleg01.wav"},
    {"MY LEG2", "My leg.", "vo/npc/male01/myleg02.wav"},
    {"NICE", "Nice.", "vo/npc/male01/nice.wav"},
    {"OH NO2", "Oh no.", "vo/npc/male01/ohno.wav"},
    {"OK", "Ok.", "vo/npc/male01/ok01.wav"},
    {"OK2", "Ok.", "vo/npc/male01/ok02.wav"},
    {"OK IM READY", "Ok, I'm ready.", "vo/npc/male01/okimready01.wav"},
    {"OK IM READY2", "Ok, I'm ready.", "vo/npc/male01/okimready02.wav"},
    {"OK IM READY3", "Ok, I'm ready!", "vo/npc/male01/okimready03.wav"},
    {"ONE FOR ME", "One for me and one for me.", "vo/npc/male01/oneforme.wav"},
    {"OUT OF YOUR WAY", "Let me get out of your way.", "vo/npc/male01/outofyourway02.wav"},
    {"HEY OVER HERE", "Hey over here!", "vo/npc/male01/overhere01.wav"},
    {"OVER THERE", "Over there!", "vo/npc/male01/overthere01.wav"},
    {"OVER THERE2", "Over there!", "vo/npc/male01/overthere02.wav"},
    {"OW", "Ow!", "vo/npc/male01/ow01.wav"},
    {"OW2", "Ow!", "vo/npc/male01/ow02.wav"},
    {"PARDON ME", "Pardon me.", "vo/npc/male01/pardonme01.wav"},
    {"PARDON ME2", "Pardon me.", "vo/npc/male01/pardonme02.wav"},
    {"EVER GONNA END", "I don't think this war is ever gonna end.", "vo/npc/male01/question01.wav"},
    {"INSURANCE", "To think, all I used to want to do was sell insurance.", "vo/npc/male01/question02.wav"},
    {"DON'T DREAM", "I don't dream anymore.", "vo/npc/male01/question03.wav"},
    {"WHEN THIS IS OVER", "When this is all over I'm...aw, who am I kidding?", "vo/npc/male01/question04.wav"},
    {"DEJAVU", "Woah, Deja vu.", "vo/npc/male01/question05.wav"},
    {"CHEESE", "Sometimes, I dream about cheese.", "vo/npc/male01/question06.wav"},
    {"FREEDOM", "You semm that? It's freedom!", "vo/npc/male01/question07.wav"},
    {"EAT A HORSE", "I could eat a horse, hooves and all.", "vo/npc/male01/question09.wav"},
    {"CAN'T BELIEVE THIS DAY", "I can't believe this day has finally come!", "vo/npc/male01/question10.wav"},
    {"NOT PART OF PLAN", "I'm pretty sure this isn't part of the plan.", "vo/npc/male01/question11.wav"},
    {"WORSE NOT BETTER", "Looks to me things are getting worse, not better.", "vo/npc/male01/question12.wav"},
    {"LIVE MY LIFE ALL OVER", "If I could live my life all over again.", "vo/npc/male01/question13.wav"},
    {"WHAT THAT REMINDS ME", "I'm not even gonna tell you what that reminds me of.", "vo/npc/male01/question14.wav"},
    {"STALKER OUT OF ME", "They're never gonna make a stalker out of me.", "vo/npc/male01/question15.wav"},
    {"CHANGE IS IN THE AIR", "Finally, change is in the air!", "vo/npc/male01/question16.wav"},
    {"YOU FEEL IT", "You feel it? I feel it!", "vo/npc/male01/question17.wav"},
    {"DON'T FEEL ANYTHING", "I don't feel anything anymore.", "vo/npc/male01/question18.wav"},
    {"SHOWER", "I can't remember the last time I had a shower.", "vo/npc/male01/question19.wav"},
    {"BAD MEMORY", "Some day, this will all be a bad memory.", "vo/npc/male01/question20.wav"},
    {"BETTING", "I'm not a betting man, but the odds are not good.", "vo/npc/male01/question21.wav"},
    {"CARE WHAT I THINK", "Doesn't anyone care what I think?", "vo/npc/male01/question22.wav"},
    {"TUNE", "I can't get this tune out of my head. *Whistling.*", "vo/npc/male01/question23.wav"},
    {"ONE OF THOSE DAYS", "I just knew it was gonna be one of those days.", "vo/npc/male01/question25.wav"},
    {"BULLSHIT", "This is bullshit.", "vo/npc/male01/question26.wav"},
    {"ATE SOMETHING BAD", "I think I ate something bad.", "vo/npc/male01/question27.wav"},
    {"HUNGRY", "God, I'm hungry.", "vo/npc/male01/question28.wav"},
    {"IM GONNAMATE", "When this is all over, I'm gonna mate.", "vo/npc/male01/question29.wav"},
    {"NO KIDS", "I'm glad there's no kids around to see this.", "vo/npc/male01/question30.wav"},
    {"CAN'T REMEMBER", "I can't remember the last time I had... well, anything.", "vo/npc/male01/question31.wav"},
    {"READY WHEN YOU ARE", "Ready when you are!", "vo/npc/male01/readywhenyouare01.wav"},
    {"READY WHEN YOU ARE2", "Ready when you are!", "vo/npc/male01/readywhenyouare02.wav"},
    {"RUN FOR YOUR LIFE", "Run for your life!", "vo/npc/male01/runforyourlife01.wav"},
    {"RUN FOR YOUR LIFE2", "Run for your life!", "vo/npc/male01/runforyourlife02.wav"},
    {"RUN FOR YOUR LIFE3", "Run for your life!", "vo/npc/male01/runforyourlife03.wav"},
    {"SCANNERS", "Scanners!", "vo/npc/male01/scanners01.wav"},
    {"SCANNERS2", "Scanners!", "vo/npc/male01/scanners02.wav"},
    {"SORRY", "Sorry.", "vo/npc/male01/sorry01.wav"},
    {"SORRY2", "Sorry.", "vo/npc/male01/sorry02.wav"},
    {"SORRY3", "Sorry.", "vo/npc/male01/sorry03.wav"},
    {"WHATEVER YOU SAY", "Whatever you say.", "vo/npc/male01/squad_affirm03.wav"},
    {"OK IM GOING", "Ok, I'm going.", "vo/npc/male01/squad_affirm04.wav"},
    {"HERE GOES", "Here goes.", "vo/npc/male01/squad_affirm05.wav"},
    {"HERE GOES NOTHING", "Here goes nothing.", "vo/npc/male01/squad_affirm06.wav"},
    {"HERE WE COME", "Here we come!", "vo/npc/male01/squad_approach02.wav"},
    {"ON OUR WAY", "On our way!", "vo/npc/male01/squad_approach03.wav"},
    {"COMING", "Coming!", "vo/npc/male01/squad_approach04.wav"},
    {"THIS WAY GANG", "This way gang!", "vo/npc/male01/squad_away01.wav"},
    {"OVER HERE", "Over here!", "vo/npc/male01/squad_away02.wav"},
    {"FOLLOW ME", "Follow me!", "vo/npc/male01/squad_away03.wav"},
    {"COME ON EVERYBODY", "Come on everybody!", "vo/npc/male01/squad_follow02.wav"},
    {"LETS GET MOVING", "Let's get moving.", "vo/npc/male01/squad_follow03.wav"},
    {"WAIT FOR US", "Wait for us!", "vo/npc/male01/squad_reinforce_group04.wav"},
    {"WAIT FOR ME", "Wait for me!", "vo/npc/male01/squad_reinforce_single04.wav"},
    {"GASP", "*Gasp.*", "vo/npc/male01/startle01.wav"},
    {"GASP2", "*Gasp.*", "vo/npc/male01/startle02.wav"},
    {"STRIDER", "Strider!", "vo/npc/male01/strider.wav"},
    {"RUN", "Run!", "vo/npc/male01/strider_run.wav"},
    {"TAKE COVER", "Take cover!", "vo/npc/male01/takecover02.wav"},
    {"THIS WILL DO NICELY", "This will do nicely.", "vo/npc/male01/thislldonicely01.wav"},
    {"UH OH", "Uh oh.", "vo/npc/male01/uhoh.wav"},
    {"UP THERE", "Up there!", "vo/npc/male01/upthere01.wav"},
    {"UP THERE2", "Up there!", "vo/npc/male01/upthere02.wav"},
    {"MUMBOJUMBO", "Enough of your mumbo jumbo.", "vo/npc/male01/vanswer01.wav"},
    {"DAMN VORTS", "Damn vorts.", "vo/npc/male01/vanswer02.wav"},
    {"NOT SURE HOW TO TAKE THAT", "I'm not sure how to take that.", "vo/npc/male01/vanswer03.wav"},
    {"TAKE THAT PERSONALLY", "Should I take that personally?", "vo/npc/male01/vanswer04.wav"},
    {"SPEAK ENGLISH", "Speak English.", "vo/npc/male01/vanswer05.wav"},
    {"GOT FROM ME", "You got that from me.", "vo/npc/male01/vanswer06.wav"},
    {"WE PUT UP WITH YOU", "That's why we put up with you.", "vo/npc/male01/vanswer07.wav"},
    {"PUT IT BETTER MYSELF", "Couldn't have put it better myself.", "vo/npc/male01/vanswer08.wav"},
    {"ALMOST MADE SENSE", "That... almost made sense.", "vo/npc/male01/vanswer09.wav"},
    {"ALMOST UNDERSTOOD", "Something must be wrong with me, I almost understood that.", "vo/npc/male01/vanswer10.wav"},
    {"GETTING USED TO VORTS", "I guess I'm getting used to you vorts.", "vo/npc/male01/vanswer11.wav"},
    {"VORT PHILOSOPHY", "None of your vort philosoply.", "vo/npc/male01/vanswer12.wav"},
    {"KILLING ME", "Stop, you're killing me.", "vo/npc/male01/vanswer13.wav"},
    {"DESERVE THIS", "What did I do to deserve this?", "vo/npc/male01/vanswer14.wav"},
    {"STOP LOOKING", "Stop looking at me like that.", "vo/npc/male01/vquestion01.wav"},
    {"NEVER GET USED TO", "Some things I just never get used to.", "vo/npc/male01/vquestion02.wav"},
    {"HOW YOU THINGS", "I don't know how you things have survived as long as you have.", "vo/npc/male01/vquestion03.wav"},
    {"HOW I ENDED UP", "Sometimes I wonder how I ended up with you.", "vo/npc/male01/vquestion04.wav"},
    {"YOURE ALRIGHT VORTY", "You're all right vorty.", "vo/npc/male01/vquestion05.wav"},
    {"VORTS ARENT HALF BAD", "You vorts aren't half bad.", "vo/npc/male01/vquestion06.wav"},
    {"PALS WITH A VORT", "If anyone would have told me I'd be pals with a vortigaunt...", "vo/npc/male01/vquestion07.wav"},
    {"WAITING FOR SOMEBODY", "You waiting for somebody?", "vo/npc/male01/waitingsomebody.wav"},
    {"WATCH OUT", "Watch out!", "vo/npc/male01/watchout.wav"},
    {"WHATCH WHAT YOURE DOING", "Watch what you're doing!", "vo/npc/male01/watchwhat.wav"},
    {"WE TRUSTED YOU", "We trusted you!", "vo/npc/male01/wetrustedyou01.wav"},
    {"WE TRUSTED YOU2", "We trusted you!", "vo/npc/male01/wetrustedyou02.wav"},
    {"WHOOPS", "Whoops.", "vo/npc/male01/whoops01.wav"},
    {"YEAH", "Yeah.", "vo/npc/male01/yeah02.wav"},
    {"BETTER RELOAD", "You better reload.", "vo/npc/male01/youdbetterreload01.wav"},
    {"YOU GOT IT", "You got it.", "vo/npc/male01/yougotit02.wav"},
    {"ZOMBIES", "Zombies!", "vo/npc/male01/zombies01.wav"},
    {"ZOMBIES2", "Zombies!", "vo/npc/male01/zombies02.wav"},
    {"HOPPERS", "Watch out for the hoppers! They're everywhere!", "vo/streetwar/barricade/male01/c17_05_hoppers.wav"},
    {"LET US THROUGH", "Let us through!", "vo/streetwar/barricade/male01/c17_05_letusthru.wav"},
    {"OPEN THE GATE", "Open the gate!", "vo/streetwar/barricade/male01/c17_05_opengate.wav"},
    {"LET US OUT", "Hey! Let us out of here!", "vo/streetwar/nexus/male01/c17_10_letusout.wav"},
    {"HORSE", "Head for the horse!", "vo/streetwar/rubble/male01/d3_c17_13_horse01.wav"},
    {"HORSE2", "We have to get to the horse!", "vo/streetwar/rubble/male01/d3_c17_13_horse02.wav"},
    {"HELP2", "Help!", "vo/streetwar/sniper/male01/c17_09_help01.wav"},
    {"HELP ME", "Help me!", "vo/streetwar/sniper/male01/c17_09_help02.wav"},
    {"SOME BODY UP THERE", "Is somebody up there?", "vo/streetwar/sniper/male01/c17_09_help03.wav"},
    {"ALMOST DONE", "If you can hold them off, I'm almost done here!", "vo/streetwar/tunnel/male01/c17_06_det02.wav"},
    {"LAST CHARGE", "Ok, last charge!", "vo/streetwar/tunnel/male01/c17_06_det03.wav"},
    {"ITS GONNA BLOW", "Stand back! It's gonna blow!", "vo/streetwar/tunnel/male01/c17_06_det04.wav"},
    {"OPEN THE DOOR", "Hey, It's me. Open the door.", "vo/streetwar/tunnel/male01/c17_06_password01.wav"},
    {"PASSWORD", "What's the password?", "vo/streetwar/tunnel/male01/c17_06_password02.wav"},
    {"PASSWORD2", "Password!", "vo/streetwar/tunnel/male01/c17_06_password03.wav"},
    {"COME ON IN", "Come on in.", "vo/streetwar/tunnel/male01/c17_06_password04.wav"},
    {"COME ACROSS", "Ok, come across.", "vo/streetwar/tunnel/male01/c17_06_plank01.wav"},
    {"COME ACROSS2", "I've got to stay here in case anyone else needs to get across.", "vo/streetwar/tunnel/male01/c17_06_plank02.wav"},
    {"MADE IT THROUGH", "I see you made it through okay. Figured you would.", "vo/streetwar/tunnel/male01/d3_c17_06_post_det04.wav"},
    {"BASE", "I wouldn't say that too loud. This is his base of operations.", "vo/trainyard/cit_tooloud.wav"},
    {"GET IN HERE3", "Get in here, quick!", "vo/trainyard/cit_blocker_getin.wav"},
    {"GET GOING5", "Get going!", "vo/trainyard/cit_blocker_go01.wav"},
    {"GO ON3", "Go on!", "vo/trainyard/cit_blocker_go02.wav"},
    {"GET GOING6", "Get going!", "vo/trainyard/cit_blocker_go03.wav"},
    {"ILL HOLD THEM", "Go on, I'll hold them!", "vo/trainyard/cit_blocker_holdem.wav"},
    {"HEAD FOR ROOF", "Keep going, head for the roof!", "vo/trainyard/cit_blocker_roof.wav"},
    {"YOU KNOCKING", "Was that you knocking? I didn't even know we still had a door.", "vo/trainyard/cit_drunk.wav"},
    {"COUPON", "This must be a mistake. I got a standard relocation coupon just like everybody else!", "vo/trainyard/cit_cell_coupon.wav"},
    {"HEY YOU", "Psst! Hey you! In here!", "vo/trainyard/cit_hall_psst.wav"},
    {"HEAD FOR ROOF2", "Head for the roof! There's no time to loose!", "vo/trainyard/cit_hall_roof.wav"},
    {"ALL I HAVE LEFT", "But this stuff, it's all I have left.", "vo/trainyard/cit_lug_allihave.wav"},
    {"IM MOVING JEEZ", "Alright I'm moving, Jeez.", "vo/trainyard/cit_lug_allright.wav"},
    {"NERVE", "I'm working up the nerve to go on.", "vo/trainyard/cit_nerve.wav"},
    {"FIND ONE", "Don't worry, they'll find one.", "vo/trainyard/cit_raid_findone.wav"},
    {"NO REASON", "They have no reason to come to our place.", "vo/trainyard/cit_raid_reason.wav"},
    {"THEN THE WHOLE BLOCK", "This is how it always starts. First a building, then the whole block.", "vo/trainyard/cit_raid_start.wav"},
    {"DON'T LIVE THERE", "Just be glad you don't live there.", "vo/trainyard/cit_raid_use01.wav"},
    {"PLACE TO STAY", "If you're looking for a place to stay, you better keep going.", "vo/trainyard/cit_raid_use02.wav"},
    {"SUIT CASE", "	I see they took your suitcase too! They can't get away with this much longer.", "vo/trainyard/cit_tookcase.wav"},
    {"END OF THE LINE", "Well, end of the line.", "vo/trainyard/cit_train_endline.wav"},
    {"DIDNT SEE YOU", "I didn't see you get on.", "vo/trainyard/cit_train_geton.wav"},
    {"RELOCATED", "No matter how many times I've been relocated, I never get used to it.", "vo/trainyard/cit_train_reloc.wav"},
    {"WATER", "Don't drink the water. They put something in it to make you forget. I don't even remember how I got here.", "vo/trainyard/cit_water.wav"},
    {"THOUGHT YOU WERE A COP", "Oh, I thought you were a cop.", "vo/trainyard/cit_window_cop.wav"},
    {"HOPE YOURE WRONG", "Just this once I hope you're wrong.", "vo/trainyard/cit_window_hope.wav"},
    {"LOOK AT THEM", "Look at them down there.", "vo/trainyard/cit_window_look.wav"},
    {"ITS ALRIGHT", "It's alright.", "vo/trainyard/husb_allright.wav"},
    {"DON'T WORRY", "Don't worry.", "vo/trainyard/husb_dontworry.wav"},
    {"GONNA BE OK", "Everything is gonna be ok.", "vo/trainyard/husb_okay.wav"},
    {"THINK OF SOMETHING", "We'll think of something.", "vo/trainyard/husb_think.wav"},
    {"ME", "Me?!", "vo/trainyard/man_me.wav"},
    {"WAIT A MINUTE", "Wait a minute.", "vo/trainyard/man_waitaminute.wav"},
    {"TAKING ME", "Where are you taking me?", "vo/trainyard/man_whereyoutakingme.wav"},
    {"STAY BACK", "Stay back, you'll sttract unwanted attention", "vo/trainyard/male01/cit_bench01.wav"},
    {"CAN'T BE SEEN", "I can't be seen talking to you, not out here.", "vo/trainyard/male01/cit_bench02.wav"},
    {"DON'T SIT", "Don't sit near me, it'll look suspicious.", "vo/trainyard/male01/cit_bench03.wav"},
    {"PIGEONS", "You're scaring off the pigeons.", "vo/trainyard/male01/cit_bench04.wav"},
    {"LINE", "The line starts at the end.", "vo/trainyard/male01/cit_foodline01.wav"},
    {"WAIT YOUR TURN", "You'll have to wait your turn like everybody else.", "vo/trainyard/male01/cit_foodline02.wav"},
    {"DAMN HUNGRY", "You gotta be damn hungry to wait in line for this crap.", "vo/trainyard/male01/cit_foodline03.wav"},
    {"JOIN CP", "I don't know about you, but I'm ready to join Civil Protection just to get a decent meal.", "vo/trainyard/male01/cit_foodline04.wav"},
    {"CUT IT OUT", "Cut it out!", "vo/trainyard/male01/cit_hit01.wav"},
    {"STOP THAT", "Stop that!", "vo/trainyard/male01/cit_hit02.wav"},
    {"WATCH IT", "Watch it will you?", "vo/trainyard/male01/cit_hit03.wav"},
    {"NO MORE", "No more.", "vo/trainyard/male01/cit_hit04.wav"},
    {"ENOUGH OF THAT", "That's enough of that!", "vo/trainyard/male01/cit_hit05.wav"},
    {"NEW IN TOWN", "New in town, aren't you?", "vo/trainyard/male01/cit_pedestrian01.wav"},
    {"KEEP IT TO YOU", "Word to the wise, keep it to youself.", "vo/trainyard/male01/cit_pedestrian02.wav"},
    {"BOTH BE IN TROUBLE", "If I talk to you out here, we'll both be in trouble.", "vo/trainyard/male01/cit_pedestrian03.wav"},
    {"CAN'T BESEEN2", "We can't be seen talking to each other.", "vo/trainyard/male01/cit_pedestrian04.wav"},
    {"LIKE TO HELP YOU", "I'd like to help you, but it's out of the question.", "vo/trainyard/male01/cit_pedestrian05.wav"},
    {"THIRD TRANSFER", "This is my third transfer this year.", "vo/trainyard/male01/cit_term_ques02.wav"},
    {"REALLY GONNA GET IT", "Oh no. Now we're really gonna get it.", "vo/trainyard/male01/cit_tvbust05.wav"},
    {"DOESNT LOOK GOOD", "This doesn't look good.", "vo/trainyard/male01/cit_window_use01.wav"},
    {"COMING IN HERE", "They're definitely coming in here.", "vo/trainyard/male01/cit_window_use02.wav"},
    {"MATTER OF TIME", "It was just a matter of time.", "vo/trainyard/male01/cit_window_use03.wav"},
    {"NEIGHBORHOOD", "Here goes the rest of the neighborhood.", "vo/trainyard/male01/cit_window_use04.wav"},
    {"CRY1", "*Cries*", "ambient/creatures/town_scared_breathing1.wav"},
    {"CRY2", "*Cries*", "ambient/creatures/town_scared_breathing2.wav"},
    {"COUGH1", "*Coughs*", "ambient/voices/cough1.wav"},
    {"COUGH2", "*Coughs*", "ambient/voices/cough2.wav"},
    {"COUGH3", "*Coughs*", "ambient/voices/cough3.wav"},
    {"COUGH4", "*Coughs*", "ambient/voices/cough4.wav"},
}

for k, v in ipairs(citizenMaleVCs) do
    Schema.voices.Add("CitizenMale", v[1], v[2], v[3])
end

Schema.voices.AddClass("CitizenMale", function(ply)
    return Schema:IsCitizen(ply) and not ply:IsFemale()
end)