local otaVoicelines = {
    {"0", "Zero", "npc/combine_soldier/vo/zero.wav"},
    {"1", "One", "npc/combine_soldier/vo/one.wav"},
    {"10", "Ten", "npc/combine_soldier/vo/ten.wav"},
    {"100", "One hundred", "npc/combine_soldier/vo/onehundred.wav"},
    {"11", "Eleven", "npc/combine_soldier/vo/eleven.wav"},
    {"12", "Twelve", "npc/combine_soldier/vo/twelve.wav"},
    {"13", "Thirteen", "npc/combine_soldier/vo/thirteen.wav"},
    {"14", "Fourteen", "npc/combine_soldier/vo/fourteen.wav"},
    {"15", "Fifteen", "npc/combine_soldier/vo/fifteen.wav"},
    {"16", "Sixteen", "npc/combine_soldier/vo/sixteen.wav"},
    {"17", "Seventeen", "npc/combine_soldier/vo/seventeen.wav"},
    {"18", "Eighteen", "npc/combine_soldier/vo/eighteen.wav"},
    {"19", "Nineteen", "npc/combine_soldier/vo/nineteen.wav"},
    {"2", "Two", "npc/combine_soldier/vo/two.wav"},
    {"20", "Twenty", "npc/combine_soldier/vo/twenty.wav"},
    {"200", "Two hundred", "npc/combine_soldier/vo/twohundred.wav"},
    {"3", "Three", "npc/combine_soldier/vo/three.wav"},
    {"30", "Thirty", "npc/combine_soldier/vo/thirty.wav"},
    {"300", "Three hundred", "npc/combine_soldier/vo/threehundred.wav"},
    {"4", "Four", "npc/combine_soldier/vo/four.wav"},
    {"40", "Fourty", "npc/combine_soldier/vo/fourty.wav"},
    {"5", "Five", "npc/combine_soldier/vo/five.wav"},
    {"50", "Fifty", "npc/combine_soldier/vo/fifty.wav"},
    {"6", "Six", "npc/combine_soldier/vo/six.wav"},
    {"60", "Sixty", "npc/combine_soldier/vo/sixty.wav"},
    {"7", "Seven", "npc/combine_soldier/vo/seven.wav"},
    {"70", "Seventy", "npc/combine_soldier/vo/seventy.wav"},
    {"8", "Eight", "npc/combine_soldier/vo/eight.wav"},
    {"80", "Eighty", "npc/combine_soldier/vo/eighty.wav"},
    {"9", "Niner", "npc/combine_soldier/vo/niner.wav"},
    {"90", "Ninety", "npc/combine_soldier/vo/ninety.wav"},
    {"ADMINISTER", "Administer", "npc/combine_soldier/vo/administer.wav"},
    {"AFFIRMATIVE", "Affirmative", "npc/combine_soldier/vo/affirmative.wav"},
    {"AFFIRMATIVE2", "Affirmative", "npc/combine_soldier/vo/affirmative2.wav"},
    {"AFFIRMATIVEGOTHIM", "Affirmative, we got him now", "npc/combine_soldier/vo/affirmativewegothimnow.wav"},
    {"ANTISEPTIC", "Anti-septic", "npc/combine_soldier/vo/antiseptic.wav"},
    {"APEX", "Apex", "npc/combine_soldier/vo/apex.wav"},
    {"BEARING", "Bearing", "npc/combine_soldier/vo/bearing.wav"},
    {"BLADE", "Blade", "npc/combine_soldier/vo/blade.wav"},
    {"BODYPACKHOLDING", "Bodypack holding", "npc/combine_soldier/vo/bodypackholding.wav"},
    {"BOOMER", "Boomer", "npc/combine_soldier/vo/boomer.wav"},
    {"BOUNCERBOUNCER", "Bouncer bouncer", "npc/combine_soldier/vo/bouncerbouncer.wav"},
    {"CLEANED", "Cleaned", "npc/combine_soldier/vo/cleaned.wav"},
    {"CLOSING", "Closing", "npc/combine_soldier/vo/closing.wav"},
    {"CONTACT", "Contact", "npc/combine_soldier/vo/contact.wav"},
    {"CONTACTCONFIRMED", "Contact confirmed", "npc/combine_soldier/vo/contactconfim.wav"},
    {"CONTACTCONFIRMEDPROSECUTING", "Contact confirmed prosecuting", "npc/combine_soldier/vo/contactconfirmprosecuting.wav"},
    {"CONTAINMENTPROCEEDING", "Containment proceeding", "npc/combine_soldier/vo/containmentproceeding.wav"},
    {"COPY", "Copy", "npc/combine_soldier/vo/copy.wav"},
    {"COPYTHAT", "Copy that", "npc/combine_soldier/vo/copythat.wav"},
    {"COVER", "Cover", "npc/combine_soldier/vo/cover.wav"},
    {"COVER2", "Cover", "npc/combine_soldier/vo/coverhurt.wav"},
    {"COVERME", "Cover me", "npc/combine_soldier/vo/coverme.wav"},
    {"DAGGER", "Dagger", "npc/combine_soldier/vo/dagger.wav"},
    {"DASH", "Dash", "npc/combine_soldier/vo/dash.wav"},
    {"DEGREES", "Degrees", "npc/combine_soldier/vo/degrees.wav"},
    {"DELIVERED", "Delivered", "npc/combine_soldier/vo/delivered.wav"},
    {"DESIGNATETARGET", "Designate target as", "npc/combine_soldier/vo/designatetargetas.wav"},
    {"DISPLACE", "Displace", "npc/combine_soldier/vo/displace.wav"},
    {"DISPLACE2", "Displace", "npc/combine_soldier/vo/displace2.wav"},
    {"ECHO", "Echo", "npc/combine_soldier/vo/echo.wav"},
    {"ENGAGEDCLEANUP", "Engaged in cleanup", "npc/combine_soldier/vo/engagedincleanup.wav"},
    {"ENGAGING", "Engaging", "npc/combine_soldier/vo/engaging.wav"},
    {"EXECUTINGRESPONSE", "Executing full response", "npc/combine_soldier/vo/executingfullresponse.wav"},
    {"EXTRACTORAWAY", "Extractor away", "npc/combine_soldier/vo/extractoraway.wav"},
    {"EXTRACTORLIVE", "Extractor is live", "npc/combine_soldier/vo/extractorislive.wav"},
    {"FIST", "Fist", "npc/combine_soldier/vo/fist.wav"},
    {"FLAREDOWN", "Flare down", "npc/combine_soldier/vo/flaredown.wav"},
    {"FLASH", "Flash", "npc/combine_soldier/vo/flash.wav"},
    {"FLATLINE", "Flatline", "npc/combine_soldier/vo/flatline.wav"},
    {"FLUSH", "Flush", "npc/combine_soldier/vo/flush.wav"},
    {"FULLACTIVE", "Full active", "npc/combine_soldier/vo/fullactive.wav"},
    {"GHOST", "Ghost", "npc/combine_soldier/vo/ghost.wav"},
    {"GOINTERCEPT", "Go active intercept", "npc/combine_soldier/vo/goactiveintercept.wav"},
    {"GOSHARP", "Go sharp", "npc/combine_soldier/vo/gosharp.wav"},
    {"GOSHARP2", "Go sharp, go sharp", "npc/combine_soldier/vo/gosharpgosharp.wav"},
    {"GRID", "Grid", "npc/combine_soldier/vo/grid.wav"},
    {"HAMMER", "Hammer", "npc/combine_soldier/vo/hammer.wav"},
    {"HARDENPOSITION", "Harden that position", "npc/combine_soldier/vo/hardenthatposition.wav"},
    {"HEAVYRESISTANCE", "Overwatch advise, we have heavy resistance", "npc/combine_soldier/vo/heavyresistance.wav"},
    {"HELIX", "Helix", "npc/combine_soldier/vo/helix.wav"},
    {"HOLDINGATCODE", "is holding at code", "npc/combine_soldier/vo/isholdingatcode.wav"},
    {"HUNTER", "Hunter", "npc/combine_soldier/vo/hunter.wav"},
    {"HURRICANE", "Hurricane", "npc/combine_soldier/vo/hurricane.wav"},
    {"ICE", "Ice", "npc/combine_soldier/vo/ice.wav"},
    {"INBOUND", "Inbound", "npc/combine_soldier/vo/inbound.wav"},
    {"INFECTED", "Infected", "npc/combine_soldier/vo/infected.wav"},
    {"ION", "Ion", "npc/combine_soldier/vo/ion.wav"},
    {"ISATCODE", "is at code", "npc/combine_soldier/vo/isatcode.wav"},
    {"ISFINALTEAMUNIT", "is final team unit, request backup", "npc/combine_soldier/vo/isfinalteamunitbackup.wav"},
    {"JET", "Jet", "npc/combine_soldier/vo/jet.wav"},
    {"JUDGE", "Judge", "npc/combine_soldier/vo/judge.wav"},
    {"KILO", "Kilo", "npc/combine_soldier/vo/kilo.wav"},
    {"LEADER", "Leader", "npc/combine_soldier/vo/leader.wav"},
    {"LOSTCONTACT", "Lost contact", "npc/combine_soldier/vo/lostcontact.wav"},
    {"MACE", "Mace", "npc/combine_soldier/vo/mace.wav"},
    {"METERS", "Meters", "npc/combine_soldier/vo/meters.wav"},
    {"MOTIONCHECK", "Motion check all radials", "npc/combine_soldier/vo/motioncheckallradials.wav"},
    {"MOVEIN", "Move in", "npc/combine_soldier/vo/movein.wav"},
    {"NECROTICS", "Necrotics", "npc/combine_soldier/vo/necrotics.wav"},
    {"NECROTICSINBOUND", "Necrotics inbound", "npc/combine_soldier/vo/necroticsinbound.wav"},
    {"NEGATIVEMOVEMENT", "Has negative movement", "npc/combine_soldier/vo/hasnegativemovement.wav"},
    {"NOMAD", "Nomad", "npc/combine_soldier/vo/nomad.wav"},
    {"NOVA", "Nova", "npc/combine_soldier/vo/nova.wav"},
    {"NOVISCON", "No viscon", "npc/combine_soldier/vo/noviscon.wav"},
    {"ONECONTAINED", "One contained", "npc/combine_soldier/vo/onecontained.wav"},
    {"ONEDOWN", "One down", "npc/combine_soldier/vo/onedown.wav"},
    {"OUTBREAK", "Outbreak", "npc/combine_soldier/vo/outbreak.wav"},
    {"OVERWATCH", "Overwatch", "npc/combine_soldier/vo/overwatch.wav"},
    {"OVERWATCHCONTAINED", "Overwatch, target contained", "npc/combine_soldier/vo/overwatchtargetcontained.wav"},
    {"OVERWATCHOVERRUN", "Overwatch, sector overrun, repeat sector overrun", "npc/combine_soldier/vo/overwatchsectoroverrun.wav"},
    {"OVERWATCHPOSSIBLEHOSTILES", "Overwatch reports possible hostiles inbound", "npc/combine_soldier/vo/overwatchreportspossiblehostiles.wav"},
    {"OVERWATCHREINFORCEMENT", "Overwatch, request reinforcement", "npc/combine_soldier/vo/overwatchrequestreinforcement.wav"},
    {"OVERWATCHRESERVEACTIVATION", "Overwatch, request reserve activation", "npc/combine_soldier/vo/overwatchrequestreserveactivation.wav"},
    {"OVERWATCHSKYSHIELD", "Overwatch, request sky shield."},
    {"OVERWATCHTEAMDOWN", "Overwatch, team is down. Sector is not controlled", "npc/combine_soldier/vo/overwatchteamisdown.wav"},
    {"PAYBACK", "Payback", "npc/combine_soldier/vo/payback.wav"},
    {"PHANTOM", "Phantom", "npc/combine_soldier/vo/phantom.wav"},
    {"PREPFORCONTACT", "Prep for contact, report in", "npc/combine_soldier/vo/prepforcontact.wav"},
    {"PROSECUTING", "Prosecuting", "npc/combine_soldier/vo/contained.wav"},
    {"PROSECUTING", "Prosecuting", "npc/combine_soldier/vo/prosecuting.wav"},
    {"QUICKSAND", "Quicksand", "npc/combine_soldier/vo/quicksand.wav"},
    {"RANGE", "Range", "npc/combine_soldier/vo/range.wav"},
    {"RANGER", "Ranger", "npc/combine_soldier/vo/ranger.wav"},
    {"RAZOR", "Razor", "npc/combine_soldier/vo/razor.wav"},
    {"READYEXTRACTORS", "Ready extractors", "npc/combine_soldier/vo/readyextractors.wav"},
    {"READYWEAPONS", "Ready weapons", "npc/combine_soldier/vo/readyweapons.wav"},
    {"READYWEAPONSHOSTILES", "Ready weapons, possible hostiles inbound", "npc/combine_soldier/vo/readyweaponshostilesinbound.wav"},
    {"REAPER", "Reaper", "npc/combine_soldier/vo/reaper.wav"},
    {"REPORTINGCLEAR", "Reporting clear", "npc/combine_soldier/vo/reportingclear.wav"},
    {"REPORTPOSITIONSCLEAR", "Report all positions clear", "npc/combine_soldier/vo/reportallpositionsclear.wav"},
    {"REPORTRADIALSFREE", "Report all radials free", "npc/combine_soldier/vo/reportallradialsfree.wav"},
    {"REQUESTMEDICAL", "Request medical", "npc/combine_soldier/vo/requestmedical.wav"},
    {"RIPCORD", "Ripcord", "npc/combine_soldier/vo/ripcord.wav"},
    {"RIPCORD2", "Ripcord, ripcord", "npc/combine_soldier/vo/ripcordripcord.wav"},
    {"SAVAGE", "Savage", "npc/combine_soldier/vo/savage.wav"},
    {"SCAR", "Scar", "npc/combine_soldier/vo/scar.wav"},
    {"SECTOR", "Sector", "npc/combine_soldier/vo/sector.wav"},
    {"SECTORNOTSECURE", "Sector is not secure", "npc/combine_soldier/vo/sectorisnotsecure.wav"},
    {"SECTORNOTSTERILE", "Confirm sector not sterile", "npc/combine_soldier/vo/confirmsectornotsterile.wav"},
    {"SECTORSECURE", "Sector is secure, no viscon", "npc/combine_soldier/vo/sectorissecurenovison.wav"},
    {"SECURE", "Secure", "npc/combine_soldier/vo/secure.wav"},
    {"SHADOW", "Shadow", "npc/combine_soldier/vo/shadow.wav"},
    {"SHARPZONE", "Sharp zone", "npc/combine_soldier/vo/sharpzone.wav"},
    {"SIGHTLINECLEAR", "Sightline is clear", "npc/combine_soldier/vo/sightlineisclear.wav"},
    {"SIGHTLINESMOVEIN", "Fix sightlines, move in", "npc/combine_soldier/vo/fixsightlinesmovein.wav"},
    {"SLAM", "Slam", "npc/combine_soldier/vo/slam.wav"},
    {"SLASH", "Slash", "npc/combine_soldier/vo/slash.wav"},
    {"SPEAR", "Spear", "npc/combine_soldier/vo/spear.wav"},
    {"STAB", "Stab", "npc/combine_soldier/vo/stab.wav"},
    {"STABILIZATIONHASSECTOR", "Stabilization team has sector control", "npc/combine_soldier/vo/stabilizationteamhassector.wav"},
    {"STABILIZATIONTEAMHOLDING", "Stabilization team holding in position", "npc/combine_soldier/vo/stabilizationteamholding.wav"},
    {"STANDINGBY", "Standing by", "npc/combine_soldier/vo/standingby].wav"},
    {"STAR", "Star", "npc/combine_soldier/vo/star.wav"},
    {"STAYALERT", "Stay alert", "npc/combine_soldier/vo/stayalert.wav"},
    {"STAYALERT2", "Stay alert, report sightlines", "npc/combine_soldier/vo/stayalertreportsightlines.wav"},
    {"STINGER", "Stinger", "npc/combine_soldier/vo/stinger.wav"},
    {"STORM", "Storm", "npc/combine_soldier/vo/storm.wav"},
    {"STRIKER", "Striker", "npc/combine_soldier/vo/striker.wav"},
    {"SUNDOWN", "Sundown", "npc/combine_soldier/vo/sundown.wav"},
    {"SUPPRESSING", "Suppressing", "npc/combine_soldier/vo/suppressing.wav"},
    {"SWARMOUTBREAK", "Swarm outbreak in sector", "npc/combine_soldier/vo/swarmoutbreakinsector.wav"},
    {"SWEEPER", "Sweeper", "npc/combine_soldier/vo/sweeper.wav"},
    {"SWEEPINGIN", "Sweeping in", "npc/combine_soldier/vo/sweepingin.wav"},
    {"SWIFT", "Swift", "npc/combine_soldier/vo/swift.wav"},
    {"SWORD", "Sword", "npc/combine_soldier/vo/sword.wav"},
    {"TARGET", "Target", "npc/combine_soldier/vo/target.wav"},
    {"TARGETCOMPROMISED", "Target compromised, move in, move in", "npc/combine_soldier/vo/targetcompromisedmovein.wav"},
    {"TARGETINEFFECTIVE", "Target in-effective", "npc/combine_soldier/vo/targetineffective.wav"},
    {"TARGETISAT", "Target is at", "npc/combine_soldier/vo/targetisat.wav"},
    {"TARGETRADIAL", "Target my radial", "npc/combine_soldier/vo/targetmyradial.wav"},
    {"TEAMDEPLOYED", "Team is deployed and scanning", "npc/combine_soldier/vo/teamdeployedandscanning.wav"},
    {"TRACKER", "Tracker", "npc/combine_soldier/vo/tracker.wav"},
    {"UNIFORM", "Uniform", "npc/combine_soldier/vo/uniform.wav"},
    {"UNITINBOUND", "Unit is inbound", "npc/combine_soldier/vo/unitisinbound.wav"},
    {"UNITMOVINGIN", "Unit is moving in", "npc/combine_soldier/vo/unitismovingin.wav"},
    {"VAMP", "Vamp", "npc/combine_soldier/vo/vamp.wav"},
    {"VISCON", "Viscon", "npc/combine_soldier/vo/viscon.wav"},
    {"VISUALEXOGEN", "Visual on exogen", "npc/combine_soldier/vo/visualonexogens.wav"},
    {"WEAPONSOFFSAFE", "Weapons off-safe, prep for contact", "npc/combine_soldier/vo/weaponsoffsafeprepforcontact.wav"},
    {"WINDER", "Winder", "npc/combine_soldier/vo/winder.wav"},
    {"WRAPITUP", "That's it, wrap it up", "npc/combine_soldier/vo/thatsitwrapitup.wav"},

    {"HOLDIT", "Hold it!", "npc/metropolice/vo/holdit.wav"},
    {"SUSPEND", "Suspend!", "npc/metropolice/vo/suspend.wav"},
    {"HOLDTHERE", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav"},
    {"XRAY", "XRay", "npc/metropolice/vo/xray.wav"},
    {"YELLOW", "Yellow!", "npc/metropolice/vo/yellow.wav"},
    {"VICE", "Vice!", "npc/metropolice/vo/vice.wav"},
    {"VICTOR", "Victor!", "npc/metropolice/vo/victor.wav"},
    {"TAP", "Tap!", "npc/metropolice/vo/tap.wav"},
    {"STICK", "Stick", "npc/metropolice/vo/stick.wav"},
    {"STORMSYSTEM", "Storm System", "npc/metropolice/vo/stormsystem.wav"},
    {"SWEEPINGSUSPECT", "Sweeping for suspect", "npc/metropolice/vo/sweepingforsuspect.wav"},
    {"SERVE", "Serve", "npc/metropolice/vo/serve.wav"},
    {"SHIT", "Shit!", "npc/metropolice/vo/shit.wav"},
    {"RODGERTHAT", "Rodger that", "npc/metropolice/vo/rodgerthat.wav"},
    {"ROLLER", "Roller!", "npc/metropolice/vo/roller.wav"},
    {"RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav"},
    {"RESTRICT", "Restrict", "npc/metropolice/vo/restrict.wav"},
    {"RESTRICTEDBLOCK", "Restricted Block", "npc/metropolice/vo/restrictedblock.wav"},
    {"REPORTLOCATIONSUSPECT", "All units report locations of suspect", "npc/metropolice/vo/allunitsreportlocationsuspect.wav"},
    {"REPORTSIGHTACCOMPLICES", "Report sights of possible accomplices", "npc/metropolice/vo/reportsightingsaccomplices.wav"},
    {"RESIDENTALBLOCK", "Residental Block", "npc/metropolice/vo/residentialblock.wav"},
    {"QUICK", "Quick!", "npc/metropolice/vo/quick.wav"},
    {"MOVEBACK", "Move back right now!", "npc/metropolice/vo/movebackrightnow.wav"},
    {"MOVEIT", "Move it", "npc/metropolice/vo/moveit2.wav"},
    {"MOVEIT2", "Move it!", "npc/metropolice/vo/moveit.wav"},
    {"MOVE", "Move", "npc/metropolice/vo/move.wav"},
    {"MOVEALONG", "Move along", "npc/metropolice/vo/movealong.wav"},
    {"JURY", "Jury!", "npc/metropolice/vo/jury.wav"},
    {"KEEPMOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav"},
    {"KING", "King!", "npc/metropolice/vo/king.wav"},
    {"LINE", "Line!", "npc/metropolice/vo/line.wav"},
    {"LOCATION", "Location", "npc/metropolice/vo/location.wav"},
    {"INPOSITION", "In position", "npc/metropolice/vo/inposition.wav"},
    {"INDUSTRIALZONE", "Industrial Zone", "npc/metropolice/vo/industrialzone.wav"},
    {"INFECTION", "Infection", "I have a 10-30 at my 10-20, respond code 2"},
    {"INFESTEDZONE", "Infested Zone", "npc/metropolice/vo/infestedzone.wav"},
    {"HERO", "Hero!", "npc/metropolice/vo/hero.wav"},
    {"HIGHREGION", "High priority region,", "npc/metropolice/vo/highpriorityregion.wav"},
    {"GRENADE!", "Grenade!", "npc/metropolice/vo/grenade.wav"},
    {"DISTRIBUTIONBLOCK", "Distribution Block", "npc/metropolice/vo/distributionblock.wav"},
    {"DOCUMENT", "Document", "npc/metropolice/vo/document.wav"},
    {"DONTMOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav"},
    {"EXAMINE", "Examine", "npc/metropolice/vo/examine.wav"},
    {"EXPIRED", "Expired", "npc/metropolice/vo/expired.wav"},
    {"COVERMEIN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav"},
    {"DBCOUNT", "DB count is", "npc/metropolice/vo/dbcountis.wav"},
    {"DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav"},
    {"CODE100", "Code 100", "npc/metropolice/vo/code100.wav"},
    {"CODE7", "Code 7", "npc/metropolice/vo/code7.wav"},
    {"CONDEMNEDZONE", "Condemned zone", "npc/metropolice/vo/condemnedzone.wav"},
    {"CONTACTWITH243", "Contact with 243 suspect, my 10-20 is", "npc/metropolice/vo/contactwith243suspect.wav"},
    {"CONTROL100", "Control is 100 percent at location, no sign of 647E", "npc/metropolice/vo/control100percent.wav"},
    {"CONTROLSECTION", "Control Section", "npc/metropolice/vo/controlsection.wav"},
    {"CONVERGING", "Converging", "npc/metropolice/vo/converging.wav"},
    {"CITIZEN", "Citizen", "npc/metropolice/vo/citizen.wav"},
    {"CLEARCODE100", "Clear and Code 100", "npc/metropolice/vo/clearandcode100.wav"},
    {"CLEARNO647", "Clear no 647, no 10-107", "npc/metropolice/vo/clearno647no10-107.wav"},
    {"BACKUP", "Backup", "npc/metropolice/vo/backup.wav"},
    {"BLOCK", "Block", "npc/metropolice/vo/block.wav"},
    {"BLOCKCOHESIVE", "Block is holding cohesive", "npc/metropolice/vo/blockisholdingcohesive.wav"},
    {"BREAKCOVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav"},
    {"ALLUNITSMOVEIN", "All units move in!", "npc/metropolice/vo/allunitsmovein.wav"},
    {"AMPUTATE", "Amputate", "npc/metropolice/vo/amputate.wav"},
    {"ANTICITIZEN", "Anti-Citizen", "npc/metropolice/vo/anticitizen.wav"},
    {"ACQUIRINGVISUAL", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav"},
    {"AFFIRMATIVE", "Affirmative", "npc/metropolice/vo/affirmative.wav"},
    {"AFFIRMATIVE2", "Affirmative", "npc/metropolice/vo/affirmative2.wav"},
}

for k, v in ipairs(otaVoicelines) do
    Schema.voices.Add("OverwatchTranshumanArm", v[1], v[2], v[3])
end

Schema.voices.AddClass("OverwatchTranshumanArm", function(ply)
    return Schema:IsOTA(ply)
end)