// https://github.com/JohnyReaper/johny-helix-plugins/blob/master/vortigaunt_stuff/sh_voices.lua

local vortVCs = {
    {"ACCOMPANY", "Gladly we accompany", "vo/npc/vortigaunt/accompany.wav"},
    {"ACIDLIONS", "Beware the acid-lions. Their corrosive spray permits quick carving of rock passages, but also serves as a strong deterrent to hive robbers like ourselves.", "vo/outland_03_04/tunnels/vort_extract_acidinfo05.wav"},
    {"AFFIRMED", "Affirmed", "vo/npc/vortigaunt/affirmed.wav"},
    {"AGREED", "Agreed", "vo/outland_03_04/tunnels/vort_extract_agreed.wav"},
    {"AGREED2", "Agreed", "vo/npc/vortigaunt/vort_grp_agree02.wav"},
    {"AH", "Ah...", "vo/npc/vortigaunt/vort_grp_agree04.wav"},
    {"AH YES", "Ah, yes.", "vo/outland_03_04/tunnels/vort_extract_ahyes.wav"},
    {"AH2", "Ah...", "vo/npc/vortigaunt/vort_grp_greetings04.wav"},
    {"AHGLAH", "Ahglah...", "vo/npc/vortigaunt/vortigese02.wav"},
    {"ALERT", "Alert!", "vo/npc/vortigaunt/alert.wav"},
    {"ALL DEAR", "We have lost all dear to us", "vo/npc/vortigaunt/alldear.wav"},
    {"ALL FOR NOW", "That is all, for now", "vo/npc/vortigaunt/allfornow.wav"},
    {"ALL IN ONE", "All in one, and one in all", "vo/npc/vortigaunt/allinoneinall.wav"},
    {"ALL WE CAN SPARE", "That is all we can spare", "vo/npc/vortigaunt/allwecanspare.wav"},
    {"ALL WE HAVE", "All we have is yours", "vo/npc/vortigaunt/allwehave.wav"},
    {"ALLOW ME", "Allow me", "vo/npc/vortigaunt/allowme.wav"},
    {"ALMOST VORTAL", "Almost vortal, this bond between you...", "vo/outland_02/junction/vort_junc_almostvortal.wav"},
    {"AN HONOR", "It is an honor", "vo/npc/vortigaunt/itishonor.wav"},
    {"ANTLION HUSBANDRY", "Antlion husbandry was once our ancestral practice", "vo/outland_03_04/tunnels/vort_extract_bond03.wav"},
    {"ANTLIONS", "Antlions!", "vo/outland_03_04/tunnels/vort_antlions_arrive_01.wav"},
    {"AS YOU WISH", "As you wish", "vo/npc/vortigaunt/asyouwish.wav"},
    {"ASSENT", "Assent.", "vo/npc/vortigaunt/assent.wav"},
    {"ASSUME NOTHING", "Assume /nothing/", "vo/npc/vortigaunt/vanswer09.wav"},
    {"ATTEMPT", "It appears they attempted an escape, but made it no farther than the abyss.", "vo/outland_06/bridge/vort_bridge_attempt.wav"},
    {"ATTEND", "Attend, now and learn to shepherd antlions with this so-called bug-bait.", "vo/coast/bugbait/vbaittrain01c.wav"},
    {"ATTEND2", "Now, attend well. Apply pressure to your pheropod, to signal the antlions in your command to follow you.", "vo/coast/bugbait/vbaittrain04.wav"},
    {"BE OF SERVICE", "Can we be of service", "vo/npc/vortigaunt/beofservice.wav"},
    {"BEG YOUR AWARENESS", "We beg your awareness...", "vo/npc/vortigaunt/vanswer14.wav"},
    {"BEHOLD", "Behold!", "vo/outland_02/junction/vort_junc_behold.wav"},
    {"BOTH PARTIES", "Headcrabs have had their way with both parties.", "vo/outland_06/bridge/vort_bridge_nogoodend02.wav"},
    {"BRIGHT FACE", "Your bright face obscures your darker mask", "vo/npc/vortigaunt/vmono_17.wav"},
    {"BY OUR HONOR", "By our honor", "vo/npc/vortigaunt/ourhonor.wav"},
    {"CALL1", "Shaaaa!", "vo/outland_01/intro/ol01_vortcall01.wav"},
    {"CALL2", "Dey'nach? Sennah 'saa razh ah!", "vo/outland_01/intro/ol01_vortcall02c.wav"},
    {"CALL3", "Dey'nahh?", "vo/outland_01/intro/ol01_vortresp01.wav"},
    {"CALL4", "Shaa!", "vo/outland_01/intro/ol01_vortresp04.wav"},
    {"CALM", "Calm Yourself", "vo/npc/vortigaunt/calm.wav"},
    {"CAN WE NOT", "Can we not convince you otherwise", "vo/npc/vortigaunt/canconvince.wav"},
    {"CANNOT HEAL", "We cannot heal a moving target", "vo/npc/vortigaunt/movingtarget.wav"},
    {"CANNOT HOPE", "But I cannot hope to bring it back alone.", "vo/outland_03_04/tunnels/vort_extract_journeydeep02.wav"},
    {"CAUTION", "Caution", "vo/npc/vortigaunt/caution.wav"},
    {"CERTAINLY", "Certainly", "vo/npc/vortigaunt/certainly.wav"},
    {"CHAA", "Chaa... Kurr? Par'aih...", "vo/outland_01/intro/vort_rbed_vemotings01.wav"},
    {"CHAFING BONDS", "We have endured these chafing bonds for eons, yet a single moment of further servitude seems intolerable!", "vo/npc/vortigaunt/vmono_21.wav"},
    {"CHASM", "Behold! Across the chasm!", "vo/outland_03_04/tunnels/vort_extract_vibchasm01.wav"},
    {"CHUAA", "Chuaa'lung gunn', chellah gurr.", "vo/npc/vortigaunt/vortigese12.wav"},
    {"CHURR", "Churr! Galih churr alla gunn'!", "vo/npc/vortigaunt/vortigese11.wav"},
    {"CLAIM YOU", "We claim you", "vo/npc/vortigaunt/weclaimyou.wav"},
    {"COMMUNION OF THE VORTESSENCE", "Communion of the vortessence, and that other: a deeper mystery. No deeper than the void itself.", "vo/npc/vortigaunt/vmono_08.wav"},
    {"COMPANION", "There is no finer companion.", "vo/outland_03_04/tunnels/vort_extract_yescompanion02.wav"},
    {"COMPANY", "We deem this company inviolable", "vo/npc/vortigaunt/vques09.wav"},
    {"CONDITION", "That condition will not last long if you plunge into the toxins below.", "vo/outland_06/bridge/vort_bridge_takeupaim01.wav"},
    {"CONSEQUENCES OF THIS STRUGGLE", "Your song we sing and shall sing for eternity. No matter the consequences of this struggle.", "vo/npc/vortigaunt/vmono_11.wav"},
    {"CONSTANT OBSTACLES", "What next in the parade of constant obstacles?", "vo/outland_03_04/tunnels/vort_extract_constantobst.wav"},
    {"CORPOREAL", "We never dream to meet you in corporeal form", "vo/npc/vortigaunt/corporeal.wav"},
    {"COURTESY", "Yes, we will vocalize in your auditory language as a matter of courtesy.", "vo/coast/vgossip_02.wav"},
    {"CRATES", "I think you will be very glad you saved those crates.", "vo/outland_03_04/tunnels/vort_extract_savedcrates02.wav"},
    {"DEDICATE OURSELVES", "We dedicate ourselves to your purpose", "vo/npc/vortigaunt/dedicate.wav"},
    {"DEFEND US", "Defend us!", "vo/outland_02/junction/vort_turret_defendus.wav"},
    {"DELUDED", "You are deluded.", "vo/npc/vortigaunt/vanswer11.wav"},
    {"DESCEND", "But how... How shall we descend?", "vo/outland_03_04/tunnels/vort_extract_howdescend.wav"},
    {"DEVICE", "That immense repellant device promises surcease from endless antlion attacks.", "vo/outland_03_04/tunnels/vort_extract_vibchasm02.wav"},
    {"DEVICE2", "Take shelter near the repellant device!", "vo/outland_05/canyon/vort_guard_alyxshelter01.wav"},
    {"DEVICE3", "A vibratory oasis!", "vo/outland_05/canyon/vort_guard_alyxshelter03.wav"},
    {"DISABLED", "I have disabled them.", "vo/outland_03_04/tunnels/vort_prone_nag_02.wav"},
    {"DISTURBED", "For now we must not be disturbed.", "vo/outland_02/junction/vort_junc_assistance03.wav"},
    {"DONE", "Done", "vo/npc/vortigaunt/done.wav"},
    {"DONT RELY", "Don't rely on it", "vo/npc/vortigaunt/vanswer08.wav"},
    {"DREAMS", "I only hope our dreams do not follow them.", "vo/outland_03_04/tunnels/vort_extract_dreamsdonotfollow02.wav"},
    {"EMPOWER US", "Empower us", "vo/npc/vortigaunt/empowerus.wav"},
    {"ENERGY EMPOWERS", "Its energy empowers us", "vo/npc/vortigaunt/energyempower.wav"},
    {"EXCELLENT", "Excellent", "vo/npc/vortigaunt/vort_excellent.wav"},
    {"EXCELLENT SHOOTING", "Excellent shooting", "vo/npc/vortigaunt/vort_excellentshooting.wav"},
    {"EXCELLENT SHOT", "Excellent shot", "vo/npc/vortigaunt/vort_excellentshot.wav"},
    {"EXCEPTIONAL", "Exceptional", "vo/npc/vortigaunt/vort_exceptional.wav"},
    {"EXCUSE OUR", "Excuse our gauche vicissitudes.", "vo/npc/vortigaunt/vanswer13.wav"},
    {"EXHAUSTED", "We have exhausted their immediate number", "vo/outland_02/junction/vort_junc_exhausted.wav"},
    {"EXTRACT AROMA", "We must try another direction... The extract aroma is weaker here.", "vo/outland_03_04/tunnels/vort_extract_wrongway05.wav"},
    {"FALSE VEILS", "It dissolves the false veils that divide the vortessence.", "vo/outland_03_04/tunnels/vort_extract_bond05.wav"},
    {"FAR DISTANT EYES", "Far distant eyes look out through yours.", "vo/npc/vortigaunt/vmono_19.wav"},
    {"FAREWELL", "Farewell", "vo/outland_02/junction/vort_junc_bye01.wav"},
    {"FAREWELL2", "Likewise and farewell. It has been an honour.", "vo/outland_06/bridge/vort_bridge_farewell.wav"},
    {"FARFETCHED", "Such a theory is hardly far-fetched.", "vo/outland_05/canyon/vort_canyon_farfetch.wav"},
    {"FEELING IS MUTUAL", "The feeling is mutual", "vo/npc/vortigaunt/vanswer16.wav"},
    {"FIGHT WITH US", "It is good now that you fight with us", "vo/npc/vortigaunt/vort_goodfightwithus.wav"},
    {"FINEST QUALITY", "Secretions of the finest quality.", "vo/outland_03_04/tunnels/vort_extract_finequality01.wav"},
    {"FOR FREEDOM", "For freedom", "vo/npc/vortigaunt/forfreedom.wav"},
    {"FORGIVENESS IS NOT OURS TO BESTOW", "We cannot forget those whose cords you cut. Forgiveness is not ours to bestow.", "vo/npc/vortigaunt/vmono_09.wav"},
    {"FORWARD", "Forward", "vo/npc/vortigaunt/forward.wav"},
    {"GALLUMLUNG", "Gallum'lung", "vo/npc/vortigaunt/vortigese09.wav"},
    {"GIVE OVER", "Give over your essense", "vo/npc/vortigaunt/giveover.wav"},
    {"GLADLY", "Gladly", "vo/npc/vortigaunt/gladly.wav"},
    {"GLORIOUS END", "To our glorious end", "vo/npc/vortigaunt/gloriousend.wav"},
    {"GO SAFELY", "Go safely", "vo/outland_02/junction/vort_junc_bye02.wav"},
    {"GREAT ANTICIPATION", "I will observe with great anticipation!", "vo/outland_03_04/tunnels/vort_extract_puzzling02.wav"},
    {"GREATER RESISTANCE", "Expect ever-greater resistance as we proceed", "vo/outland_03_04/tunnels/vort_extract_keen02.wav"},
    {"GRIEF AND JUBILATION", "You have brought us grief and jubilation beyond measure...", "vo/npc/vortigaunt/vmono_12.wav"},
    {"GUARDIAN", "The guardian...", "vo/outland_05/canyon/vort_guard_surfacesighting.wav"},
    {"GUARDIAN2", "The guardian!", "vo/outland_05/canyon/vort_guard_killit_nag_09.wav"},
    {"GUARDIAN3", "Remember! Do not kill the guardian or the extract will be ruined!", "vo/outland_03_04/tunnels/vort_extract_donotkill.wav"},
    {"GUARDIAN4", "The guardian bars our way, but now we are free to destroy it.", "vo/outland_05/canyon/vort_guard_killit_nag_03.wav"},
    {"GUARDIAN5", "If we are to survive, this guardian must now die.", "vo/outland_05/canyon/vort_guard_killit_nag_06.wav"},
    {"GUARDIAN6", "Kill the guardian now!", "vo/outland_05/canyon/vort_guard_killit_nag_08.wav"},
    {"GUARDIAN7", "Ah, the ancient guardian! Retrieving the extract may not be unchallenging.", "vo/outland_03_04/tunnels/vort_extract_ancientguard.wav"},
    {"GUARDIAN8", "The guardian's presence guarantees the nearness of larval clusters. They are commonly posted near the young.", "vo/outland_03_04/tunnels/vort_extract_nearness.wav"},
    {"GUARDIAN9", "The guardian is enraged over our theft of the extract.", "vo/outland_05/canyon/vort_canyon_guardianrage01.wav"},
    {"GULANGA", "Gulanga", "vo/npc/vortigaunt/vortigese08.wav"},
    {"GUNN", "Gunn", "vo/npc/vortigaunt/vortigese07.wav"},
    {"HALT", "Halt", "vo/npc/vortigaunt/halt.wav"},
    {"HARDEST WORK", "You have done the hardest work, admitting entrance to this chamber.", "vo/outland_03_04/tunnels/vort_extract_hardwork03.wav"},
    {"HEADY AROMA", "Ah! Such quantities of the larvae... Such a heady aroma.", "vo/outland_03_04/tunnels/vort_extract_larvalaroma.wav"},
    {"HELP YOU", "We will help you", "vo/npc/vortigaunt/wewillhelp.wav"},
    {"HERE", "Here", "vo/npc/vortigaunt/here.wav"},
    {"HINDER OUR PROGRESS", "If it tries to hinder our progress, we will have no choice but to kill it.", "vo/outland_05/canyon/vort_canyon_guardianrage02.wav"},
    {"HM", "Hm...", "vo/npc/vortigaunt/vort_grp_agree03.wav"},
    {"HOLD", "Hold", "vo/npc/vortigaunt/hold.wav"},
    {"HOLD STILL", "Hold still", "vo/npc/vortigaunt/holdstill.wav"},
    {"HONOUR IS OURS", "The honour is ours", "vo/npc/vortigaunt/honorours.wav"},
    {"HOPE", "Hope is in sight", "vo/npc/vortigaunt/vques03.wav"},
    {"HOPELESS", "Our cause seems hopeless", "vo/npc/vortigaunt/hopeless.wav"},
    {"HOPES AND DREAMS", "How many are there in you? Whose hopes and dreams do you encompass?", "vo/npc/vortigaunt/vmono_28.wav"},
    {"HUMAN NEEDED", "A Human is needed...", "vo/outland_03_04/tunnels/vort_extract_humanmark.wav"},
    {"HUMANS", "You humans, always in the qualidity.", "vo/npc/vortigaunt/vques08.wav"},
    {"I DESCEND", "I descend!", "vo/outland_03_04/tunnels/vort_04_elevator_descend_01.wav"},
    {"IF YOU MOVE", "If you move, we cannot help you", "vo/npc/vortigaunt/ifyoumove.wav"},
    {"IMMEASURABLE LOSS", "We have averted an immeasurable loss...", "vo/outland_02/junction/vort_junc_immeasurable.wav"},
    {"INDEED", "Indeed", "vo/npc/vortigaunt/vort_grp_agree06.wav"},
    {"JOIN ME", "Join me", "vo/outland_03_04/tunnels/vort_extract_joinmefm02.wav"},
    {"JOIN NOW", "Join now as we imbibe the extract.", "vo/outland_03_04/tunnels/vort_extract_imbibe.wav"},
    {"JUST AS WELL", "It is just as well", "vo/npc/vortigaunt/vanswer04.wav"},
    {"JUST SO", "Just so", "vo/coast/vgossip_04.wav"},
    {"JUST SO2", "Just so", "vo/npc/vortigaunt/vort_grp_agree01.wav"},
    {"KALAGH", "Kalagh!", "vo/npc/vortigaunt/vort_attack21.wav"},
    {"KEEN", "The antlions are keen to our presence", "vo/outland_03_04/tunnels/vort_extract_keen01.wav"},
    {"KILL IT", "At this time, you may kill it without consequence", "vo/outland_05/canyon/vort_guard_killit.wav"},
    {"KILLED ANTLIONS", "We have killed many antlions", "vo/outland_02/junction/vort_junc_killedmanyyet01.wav"},
    {"KIN SOME DISTANCE", "My kin are still some distance away", "vo/outland_02/junction/vort_junc_assistance02.wav"},
    {"KNOW YOU", "We know you", "vo/npc/vortigaunt/weknowyou.wav"},
    {"LARVAL EXTRACT", "Ah, excellent.. A bounty of larval extract.", "vo/outland_03_04/tunnels/vort_extract_bounty01.wav"},
    {"LARVAL PELLET", "I see you too appreciate the larval pellet's properties.", "vo/outland_03_04/tunnels/vort_squishgrub04.wav"},
    {"LEAD ON", "Lead on", "vo/npc/vortigaunt/leadon.wav"},
    {"LEAD US", "Lead us", "vo/npc/vortigaunt/leadus.wav"},
    {"LIE STILL", "Lie still...", "vo/outland_02/junction/vort_junc_liestill.wav"},
    {"LIKEWISE", "Likewise, we assure", "vo/npc/vortigaunt/vanswer15.wav"},
    {"LOST ALL DEAR", "We have lost all dear to us...", "vo/npc/vortigaunt/vques01.wav"},
    {"LUNG", "Lung", "vo/npc/vortigaunt/vortigese05.wav"},
    {"MAKE HASTE", "Make haste", "vo/outland_03_04/tunnels/vort_extract_makehaste.wav"},
    {"MATTER HOURS", "A matter of hours", "vo/outland_02/junction/vort_junc_matterhours.wav"},
    {"MINDS IN YOUR MIND", "Could you but see the eyes inside your own, the minds in your mind, you would see how much we share.", "vo/npc/vortigaunt/vmono_29.wav"},
    {"MIRACULOUS", "Miraculous secretion.", "vo/outland_03_04/tunnels/vort_extract_pharynx.wav"},
    {"MOMENT LONGER", "A moment longer", "vo/outland_02/junction/vort_junc_momentlonger.wav"},
    {"MOST PRIZED", "The creatures exude many valuable compounds... But the extract is the most prized by far...", "vo/outland_03_04/tunnels/vort_extract_bond04.wav"},
    {"MOUNTED GUN", "This mounted gun may prove useful.", "vo/outland_06/bridge/vort_bridge_thismountgun.wav"},
    {"NECTARIUM", "I will make the journey to seek the extract deep within the nest, in the sacred nectarium.", "vo/outland_03_04/tunnels/vort_extract_journeydeep01.wav"},
    {"NEXT MATTER", "Now to the next matter of urgency", "vo/outland_02/junction/vort_junc_nextmatter.wav"},
    {"NO DISTANCE BETWEEN US", "There is no distance between us. No false veil of time or space may intervene.", "vo/npc/vortigaunt/vmono_04.wav"},
    {"NO FEAR", "No fear, we will put you on the right road", "vo/outland_02/junction/vort_junc_rightroad.wav"},
    {"NO GOOD END", "But came to no good end themselves.", "vo/outland_06/bridge/vort_bridge_nogoodend01.wav"},
    {"NO GRATITUDE", "Our bonds are of nature, and require no gratitude.", "vo/outland_06/bridge/vort_bridge_honored.wav"},
    {"NO PULSE", "No pulse!", "vo/outland_02/junction/vort_junc_nopulse01.wav"},
    {"NO TIME", "There is no time, more antlions approach", "vo/outland_02/junction/vort_junc_object.wav"},
    {"NODE NEXUS", "Node and nexus, feed upon this life!", "vo/npc/vortigaunt/nodenexus.wav"},
    {"NOT THE FIRST", "You're not the first to harbor such illusions", "vo/npc/vortigaunt/vanswer02.wav"},
    {"NOW ATTACK", "Now attack!", "vo/outland_03_04/tunnels/vort_prone_nag_03.wav"},
    {"OBSERVE", "Observe how they fight on below, heedless of our escape...", "vo/outland_03_04/tunnels/vort_extract_observefight.wav"},
    {"OCCUPIED", "Our hands are occupied", "vo/outland_01/intro/vort_rbed_letsgo01b.wav"},
    {"OF THE SORT", "Nothing of the sort", "vo/npc/vortigaunt/vanswer10.wav"},
    {"ONE BETWEEN THE WORLDS", "For a brief time you joined us, you were one between the worlds.", "vo/npc/vortigaunt/vmono_07.wav"},
    {"ONWARD", "Onward", "vo/npc/vortigaunt/onward.wav"},
    {"OPAQUE", "Your mind is opaque...", "vo/npc/vortigaunt/opaque.wav"},
    {"OPPOSITE", "We believe the opposite", "vo/npc/vortigaunt/vanswer03.wav"},
    {"OUR DELAY", "Our delay, regrettable...", "vo/outland_02/junction/vort_junc_weweredelayed.wav"},
    {"OUR PLACE IS HERE", "Our place is here", "vo/npc/vortigaunt/ourplacehere.wav"},
    {"PASS ON", "Pass on", "vo/npc/vortigaunt/passon.wav"},
    {"PAY IN KIND", "The Combine will pay in kind for their depravity.", "vo/npc/vortigaunt/vques02.wav"},
    {"PERSEVERE", "This is more than anyone can bare... But, we will persevere", "vo/npc/vortigaunt/persevere.wav"},
    {"PESSIMISM", "Such pessimism will doom us all", "vo/npc/vortigaunt/vques05.wav"},
    {"PITY", "Pity the generator that requires a Vortigaunt to operate it.", "vo/outland_03_04/tunnels/vort_extract_pitythegen.wav"},
    {"PLEASANT UNDERFOOT", "They are quite pleasant underfoot, are they not?", "vo/outland_03_04/tunnels/vort_squishgrub01.wav"},
    {"PLEASED TO SEE", "I am pleased to see at least you are unharmed.", "vo/outland_01/intro/vort_rbed_freeman02.wav"},
    {"PLEASING SOUND", "Ah, such a pleasing sound and sensation.", "vo/outland_03_04/tunnels/vort_squishgrub02.wav"},
    {"PLENITUDE", "It is all one in the plenitude", "vo/npc/vortigaunt/vanswer18.wav"},
    {"POET", "Our finest poet describes it thus... Gallum gaka lillimah.", "vo/npc/vortigaunt/poet.wav"},
    {"POIGNANT", "A poignant scene... an eternity's repose. It brings peaceful thoughts, does it not?", "vo/outland_03_04/tunnels/vort_extract_chairman.wav"},
    {"POWERLESS", "The gun would appear to be powerless.", "vo/outland_06/bridge/vort_bridge_depleted02.wav"},
    {"PREVAIL", "We shall prevail", "vo/npc/vortigaunt/prevail.wav"},
    {"PROPITIOUS", "Propitious alliance", "vo/npc/vortigaunt/propitious.wav"},
    {"PURPOSE IS MUTUAL", "Our purpose is mutual", "vo/npc/vortigaunt/mutual.wav"},
    {"QUIET THEM", "We shall quiet them", "vo/outland_02/junction/vort_junc_quietthem.wav"},
    {"REASON FOR DELAY", "Is there reason for delay", "vo/npc/vortigaunt/reasondelay.wav"},
    {"REGRETTABLE", "This is regrettable...", "vo/npc/vortigaunt/regrettable.wav"},
    {"REGRETTABLY TRUE", "Regrettably true...", "vo/outland_11a/silo/vort_silo_regrettablytrue.wav"},
    {"REMAIN", "We will remain, if you so instruct", "vo/npc/vortigaunt/willremain.wav"},
    {"RETURN ALL IN ONE", "Return to the all-in-one", "vo/npc/vortigaunt/returntoall.wav"},
    {"RETURN VOID", "Return to the void", "vo/npc/vortigaunt/returnvoid.wav"},
    {"RIPE", "The scent of ripe perfection beckons.", "vo/outland_03_04/tunnels/vort_extract_hardwork01.wav"},
    {"RISE", "Now... Try carefully to rise", "vo/outland_02/junction/vort_junc_rise.wav"},
    {"SACRIFICE", "What seems to you a seems to you a sacrifice is merely, to us, an oscillation. We do not fear the interval of darkness.", "vo/npc/vortigaunt/vmono_26.wav"},
    {"SAD FATE", "The sad fate of these others is our good fortune", "vo/outland_03_04/tunnels/vort_breakweb02.wav"},
    {"SATISFACTION", "Satisfaction...", "vo/npc/vortigaunt/satisfaction.wav"},
    {"SAVE YOURSELF", "Save yourself!", "vo/outland_03_04/tunnels/vort_extract_tothelift02.wav"},
    {"SCENT OF EXTRACT", "A wind from below, bears the scent of extract... The stuff we seek lies at the bottom of this pit.", "vo/outland_03_04/tunnels/vort_extract_wind.wav"},
    {"SENTRIES", "I do not see their sentries.", "vo/outland_05/canyon/vort_canyon_enclavesentries02.wav"},
    {"SENTRIES2", "Puzzling. The sentries should have spotted us by now.", "vo/outland_05/canyon/vort_canyon_puzzling.wav"},
    {"SERVE", "We live to serve", "vo/npc/vortigaunt/livetoserve.wav"},
    {"SERVE BETTER", "Perhaps we will serve you better here", "vo/npc/vortigaunt/servebetterhere.wav"},
    {"SHALL NOT BE FORGOTTEN", "If not, your sacrifice shall not be forgotten.", "vo/outland_01/intro/vort_separation_goodbye03.wav"},
    {"SHARP SPUR OF HOPE", "That sharp spur of hope has not dulled to this day. For once the lesser master lay defeated, we knew the greater must also fall in time.", "vo/npc/vortigaunt/vmono_15.wav"},
    {"SHELTERED LOCATION", "My kin will meet us at a sheltered location beneath the surface", "vo/outland_01/intro/vort_rbed_companions01.wav"},
    {"SIB", "We call you sib, although your mind and meaning are a mystery to us.", "vo/npc/vortigaunt/vmono_18.wav"},
    {"SKILLS ARE FORMIDABLE", "Your skills are formidable", "vo/npc/vortigaunt/vort_skillsformidable.wav"},
    {"SLIPPED OUR YOKE", "How often have we slipped our yoke, only to find it choking us again.", "vo/npc/vortigaunt/vmono_22.wav"},
    {"SOMETHING SECRET STEERS US BOTH", "Something secret steers us both. We shall not name it.", "vo/npc/vortigaunt/vmono_20.wav"},
    {"SPECULATION", "Idle speculation", "vo/npc/vortigaunt/vanswer06.wav"},
    {"STAND CLEAR", "Stand clear", "vo/npc/vortigaunt/standclear.wav"},
    {"STILL HERE", "We are still here...", "vo/npc/vortigaunt/stillhere.wav"},
    {"SUBMERSION", "This will necessitate deep submersion in the vortessence.", "vo/outland_03_04/tunnels/vort_extract_injuriesdeep02.wav"},
    {"SUCCESS", "Success", "vo/outland_01/intro/vort_separation_success02.wav"},
    {"SUCCULENT", "The grubs are nothing if not... Succulent.", "vo/outland_03_04/tunnels/vort_squishgrub03.wav"},
    {"SUMMON MY KIN", "Let me summon my kin", "vo/outland_01/intro/vort_rbed_freeman05.wav"},
    {"SURGE", "We surge", "vo/npc/vortigaunt/surge.wav"},
    {"SURVIVED DARKER TIMES", "We have survived darker times", "vo/npc/vortigaunt/vques06.wav"},
    {"SURVIVED WORSE", "We have survived worse across the ages", "vo/npc/vortigaunt/seenworse.wav"},
    {"TAHH", "Tahh", "vo/npc/vortigaunt/vortigese03.wav"},
    {"TAKE A MOMENT", "This should only take a moment", "vo/outland_03_04/tunnels/vort_extract_bounty02.wav"},
    {"TAKE OUR STAND", "We take our stand beside you here, upon this miserable rock.", "vo/npc/vortigaunt/vmono_24.wav"},
    {"TALISMAN OF VICTORY", "With you beside us, a talisman of victory, the day of freedom draws nigh.", "vo/npc/vortigaunt/vmono_16.wav"},
    {"TAPESTRY", "We are a tapestry woven of vortessence. It is the same for you if only you would see it.", "vo/npc/vortigaunt/vmono_27.wav"},
    {"TETHER CUT", "The tether is cut", "vo/npc/vortigaunt/tethercut.wav"},
    {"THAT IS ALL", "That is all", "vo/npc/vortigaunt/thatisall.wav"},
    {"THE EXTRACT", "The extract!", "vo/outland_03_04/tunnels/vort_extract_theextract02.wav"},
    {"THE EXTRACT2", "The extract!", "vo/outland_03_04/tunnels/vort_extract_theextract03.wav"},
    {"THE WAY AHEAD IS DARK", "The way ahead is dark for the moment..", "vo/npc/vortigaunt/vmono_25.wav"},
    {"THIS BODY", "This body is yours to command", "vo/npc/vortigaunt/bodyyours.wav"},
    {"THIS MUCH", "We expected this much", "vo/npc/vortigaunt/vanswer05.wav"},
    {"TO THE VOID", "To the void with you", "vo/npc/vortigaunt/tothevoid.wav"},
    {"TOTAL VICTORY", "Let this war end in either total victory or our extinction. No further compromise shall we allow.", "vo/npc/vortigaunt/vmono_23.wav"},
    {"TOUCHING", "Your concern is touching", "vo/npc/vortigaunt/vanswer07.wav"},
    {"TRACES", "Such traces of former habitation somehow sadden me.", "vo/outland_03_04/tunnels/vort_extract_traces.wav"},
    {"TRAITS", "You bear some traits we thought innate to vortikind.", "vo/outland_03_04/tunnels/vort_extract_bond02.wav"},
    {"TRAUMATIC INJURY", "The Combine Hunters cause traumatic injury.", "vo/outland_02/junction/vort_junc_badlyinjured02.wav"},
    {"TRAVEL WELL", "Travel well", "vo/outland_02/junction/vort_junc_bye03.wav"},
    {"TROUBLE US NO MORE", "That one shall trouble us no more", "vo/npc/vortigaunt/troubleus.wav"},
    {"TURNING POINT", "This marks a turning-point", "vo/npc/vortigaunt/vques04.wav"},
    {"TURRLUNG", "Turr, lung gurr chalachurr gunn, gong lurr...", "vo/npc/vortigaunt/vortigese13.wav"},
    {"UNACCUSTOMED", "This is unaccustomed", "vo/npc/vortigaunt/vanswer17.wav"},
    {"UNCONVINCED", "We remain unconvinced", "vo/npc/vortigaunt/vanswer01.wav"},
    {"UNDER ATTACK", "We are under attack!", "vo/outland_02/junction/vort_turret_helpcall04.wav"},
    {"UNDESERVING", "Undeserving of consciousness", "vo/npc/vortigaunt/undeserving.wav"},
    {"UNFLATTERING", "Unless we wish to say unflattering things about you.", "vo/coast/vgossip_03.wav"},
    {"UNITY", "Unity of purpose; the shattering of common shackles, a single road we tread.", "vo/npc/vortigaunt/vmono_10.wav"},
    {"URGENT ERRAND", "I fear a more urgent errand demands our attention.", "vo/outland_06/bridge/vort_bridge_hunt01.wav"},
    {"URGENT NEED", "They will understand our urgent need.", "vo/outland_05/canyon/vort_canyon_reside02.wav"},
    {"VORTICOUGH", "Weeeeeeeeeeeeeeeeeah-uh *Coughing*", "npc/vort/vort_pain3.wav"},
    {"WE ARE HONORED", "We are honoured", "vo/npc/vortigaunt/wehonored.wav"},
    {"WE ARE YOURS", "We are yours", "vo/npc/vortigaunt/weareyours.wav"},
    {"WE FEAR", "We fear we have failed you", "vo/npc/vortigaunt/fearfailed.wav"},
    {"WE FOLLOW YOU", "To our honor, we follow you", "vo/npc/vortigaunt/honorfollow.wav"},
    {"WE HAVE DREAMED", "We have dreamed of this moment", "vo/npc/vortigaunt/dreamed.wav"},
    {"WE KNIT", "We knit shattered bone, and restore circulatory integrity", "vo/outland_02/junction/vort_junc_knit.wav"},
    {"WE NEED HELP", "We need help!", "vo/outland_02/junction/vort_turret_helpcall01"},
    {"WE REQUIRE EXTRACT", "We require... The larval extract.", "vo/outland_03_04/tunnels/vort_extract_werequire.wav"},
    {"WE SHARE", "We shall share the Vortessence", "vo/npc/vortigaunt/weshare.wav"},
    {"WE STAY", "Here we stay", "vo/npc/vortigaunt/herewestay.wav"},
    {"WELL IN HAND", "I have the situation well in hand!", "vo/outland_03_04/tunnels/vort_extract_tothelift03.wav"},
    {"WELL STATED", "Well stated", "vo/npc/vortigaunt/vort_grp_agree07.wav"},
    {"WHAT HARM", "What harm has come?", "vo/outland_01/intro/vort_rbed_whatharm.wav"},
    {"WHERE", "Where", "vo/npc/vortigaunt/ware.wav"},
    {"WHERE TO NOW", "Where to, now?... And to what end", "vo/npc/vortigaunt/whereto.wav"},
    {"WISH YOU WERE", "We wish you were right...", "vo/npc/vortigaunt/vanswer12.wav"},
    {"WITH PLEASURE", "With pleasure", "vo/npc/vortigaunt/pleasure.wav"},
    {"WORK TOGETHER", "It is good now that we work together", "vo/npc/vortigaunt/vort_goodtogether.wav"},
    {"WORTHLESS", "Our life is worthless... Unless spent on freedom", "vo/npc/vortigaunt/worthless.wav"},
    {"YES", "Yes", "vo/npc/vortigaunt/yes.wav"},
    {"YES FORWARD", "Yes, forward", "vo/npc/vortigaunt/yesforward.wav"},
    {"YES2", "Yes", "vo/npc/vortigaunt/vort_grp_agree05.wav"},
    {"YET MANY REMAIN", "Yet many more remain", "vo/outland_02/junction/vort_junc_killedmanyyet02.wav"},
}

for k, v in ipairs(vortVCs) do
    Schema.voices.Add("Vortigaunt", v[1], v[2], v[3])
end

Schema.voices.AddClass("Vortigaunt", function(ply)
	return Schema:IsVortigaunt(ply)
end)